govuk-one-login/ipv-cri-address-api

- build.gradle
- deploy.sh
- deploy/template.yaml
- lambdas/session/build.gradle
- lambdas/session/src/main/java/uk/gov/di/ipv/cri/address/api/handler/SessionHandler.java
- lambdas/session/src/main/resources/log4j2.xml
- lib/build.gradle
Allow lambdas in this API to set metrics and structured logging.
Update gradle config to add powertools, which provides that structured logging and metrics setting.
deploy a stack to the dev env, and send a message to the API gateway with a body like:
````
{
"response_type": "code",
"client_id": "ipv-core",
"state": "state",
"redirect_uri": "https://www.example/com/callback",
"request": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0dCIsImlhdCI6MTUxNjIzOTAyMn0.SbcN-ywpLObhMbbaMCtW1Un8LYhQzHsEth9LvTk4oQQ"
}
````
You should get back a session id on a 201 status code.
Now check cloudwatch for a log event in json format (structured) that looks like:
````
{
"instant": {
"epochSecond": 1646240418,
"nanoOfSecond": 189936000
},
"thread": "main",
"level": "INFO",
"loggerName": …
```
> KBV-221 Set metrics and structured logging on Address API

- deploy.sh
- deploy/template.yaml
Add a global CodeSigningConfigArn that allows the code signing config to land per lambda
(also move some parameters from below the conditions block)
> Set a global CodeSigningConfigArn for code signing config

- deploy/template.yaml
Fix  sam template key I removed 🙄
> Fix  key I removed

- .github/workflows/deploy.yml
- deploy/template.yaml
Added deploy to the build environment
To deploy to the new build environmemnt
- [KBV-259](https://govukverify.atlassian.net/browse/KBV-259)
Secrets to be added to README later
> [KBV-259] initial build deployment

- .github/workflows/deploy.yml
- README.md
Fix typo and update the readme
Deployment failed due to typo and README needed updating with secrets
- [KBV-259](https://govukverify.atlassian.net/browse/KBV-259)
> [KBV-259] fix typo and update README

- .github/workflows/deploy.yml
fix SAM build
To enable the build
- [KBV-259](https://govukverify.atlassian.net/browse/KBV-259)
None
> [KBV-259] fix sam build

- deploy/template.yaml
* Reference the Environment property correctly to provide api gateway stage name
* Normalise the api name to kebab case
> BAU Ref the Environment for Address CRI api gateway stage name

- deploy.sh
- deploy/template.yaml
deploy to dev without code signing config.
* remove sam deploy `--signing-profiles` flag for dev deploy script
* set empty code signing config when Environment is dev
> BAU Fi Deploy to address CRI dev without code signing

- deploy/template.yaml
Export the Address API base url from the API CF stack - this value can then be imported by the frontend.
Added a CloudFormation export.
https://github.com/alphagov/di-ipv-cri-address-front/pull/67
https://github.com/alphagov/di-ipv-config/pull/216
- [KBV-270](https://govukverify.atlassian.net/browse/KBV-270)
> KBV-270 Prefix stackname to CloudFormation export

- infrastructure/lambda/template.yaml
Update the output for the Address function to use new EnvironmentName variable
> BAU - Fix SAM Deploy Output

- .github/workflows/post-merge-deploy-to-dev.yml
- infrastructure/lambda/template.yaml
The SAM template was using EnvironmentName as the environment parameter, this has been changed to Environment
The platform team's implementation is expecting the parameter to be named Environment
- [KBV-287](https://govukverify.atlassian.net/browse/KBV-287)
None
> [KBV-287] update environment parameter name

- .github/workflows/post-merge-package-for-build.yml
- infrastructure/lambda/template.yaml
Add AddressFunction to the set of fns that are signed by the signing profile
> KBV-237 Add AddressFunction to be signed by signing profile

- .github/workflows/post-merge-deploy-to-dev.yml
- README.md
Update Dev deployment process to match build
To enable development and testing in a like for like environment
- [KBV-302](https://govukverify.atlassian.net/browse/KBV-302)
KBV and Fraud API CD process will need to be updated/created to match.
> [KBV-302] deploy to dev using platform teams process

- .github/workflows/post-merge-deploy-to-dev.yml
Update to use dev bucket environment name
Action was still referencing old name
- [KBV-302](https://govukverify.atlassian.net/browse/KBV-302)
None
> [KBV-302] Update source bucket environment variable

- infrastructure/lambda/template.yaml
Add parameters for the VC issuer, per environment.
This will help with story KBV-301, which will set the VC issuer.
- [KBV-317](https://govukverify.atlassian.net/browse/KBV-317)
> KBV-317 Add parameters for the VC issuer, per environment

- infrastructure/lambda/template.yaml
Adding access-token-index including a projection on the addresses field
> BAU: Re-added access-token-index

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
Added auto generation of function signing configurations to post merge workflows.
Remove requirement to manually add/remove signing configurations to/from the workflows when functions are added/removed which prevents unexpected deployment errors in build. 
- [KBV-326 ](https://govukverify.atlassian.net/browse/KBV-326)
None
> [KBV-326] post merge auto signing config

- infrastructure/lambda/api.yaml
- infrastructure/lambda/template.yaml
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AccessTokenService.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifier.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifierTest.java
* Log API gateway requests including body payloads
* Remove validation of client_id in token request (it isn't sent)
* Remove validation of `nbf` in token request (it isn't sent)
* Set client id as ipv-core for all dev clients
- [KBV-300](https://govukverify.atlassian.net/browse/KBV-300)
> KBV-300 fix token request

- infrastructure/lambda/template.yaml
Remove API gateway logging account and role (for now) as it breaks the CodeBuild pipeline
> Fix: Remove API gateway logging account and role (for now)

- lib/src/main/java/uk/gov/di/ipv/cri/address/library/constants/RequiredClaims.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AccessTokenService.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressSessionService.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifier.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AccessTokenServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifierTest.java
Added claims set by creating an enum `RequiredClaims` and changed method signature `verifyJWT` to accept required claims as a list of strings.
- [KBV-347](https://govukverify.atlassian.net/browse/KBV-347)
> Make nbf check configurable

- lib/src/main/java/uk/gov/di/ipv/cri/address/library/models/CanonicalAddress.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/VerifiableCredentialService.java
Remove now obsolete method and force addresses to be serialized by Jackson before passing to the claim
> [KBV-349] - Fix invalid cast

- build.gradle
- infrastructure/lambda/api.yaml
- infrastructure/lambda/template.yaml
- lambdas/jwkset/build.gradle
- lambdas/jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetHandler.java
- lambdas/jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/KMSService.java
- lambdas/jwkset/src/test/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetHandlerTest.java
- lambdas/jwkset/src/test/java/uk/gov/di/ipv/cri/address/api/handler/KMSServiceTest.java
- settings.gradle
Publish JWKSet of public keys so that clients can easily find how to encrypt for the CRI, and validate the signature of the Verifiable Credential.
The url for the JWKSet is available from an AWS API call like `aws cloudformation describe-stacks --stack-name .... `
A sample response is:
````
{
"keys": [
{
"kty": "EC",
"use": "SIGN_VERIFY",
"crv": "P-256",
"kid": "4ae92735-e00f-4abb-b853-fc834e8f8aa4",
"x": "gh1ghVk_Q8TeTMRnypAFeX9eQHwH20R9zgakPjgZUX4",
"y": "Z3Ee-z2CVanVrqqBZRLsjJAr0nm6AEr6cp7Acbo6HDA"
},
{
"kty": "RSA",
"e": "AQAB",
"use": "ENCRYPT_DECRYPT",
"kid": "7fd1524b-24a1-43b9-83ec-7b62ab24f9f0",
"n": "lqb_O2ya9uCBHzJhv9EQjKjXgIdF1HI_G9mu5LUuKHJeksu7du-t0hSzSdF_ItBYap5JaYwMago7lgY4OHOULiNWDcVPyL1-KirITl93aK8Bce5uuZC9-9ZllxdeYgY2cNu5cTmaRVwWyEUsGVGiHBKKnFuw8xmpood-2BD9k6Sh5mkRrNrGyd …
```
> KBV-363 Publish JWKSet of public keys

- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AccessTokenServiceTest.java
A the moment it appears that ApiGateway Model validation does not
work for x-www-form-urlencoded payloads this PR adds more test coverage
for that which the ApiGateway validation would have flagged
> BAU: Add more test In the Absence of ApiGateway validation

- infrastructure/lambda/template.yaml
Fix staging, int and prod audience for Address CRI
> KBV-360 Fix staging, int and prod audience for Address CRI

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/error/ErrorResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
There were some commented out tests and added more test coverage 
for AWS dynamodb server error
> BAU: More test coverage for IssueCredentialHandler

- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifier.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifierTest.java
Remove check of issuer against a value configured in our SSM params - this is temporary in order to get a staging journey with IPV Core through ;) 
- [KBV-XXXX](https://govukverify.atlassian.net/browse/KBV-XXX)
> KBV-360 Remove issuer check on JWTVerifier for now

- infrastructure/lambda/api.yaml
Change the credential/issue method to POST, to bring it inline with the method IPV Core is using
> KBV-360 Change the credential/issue method to POST

- lambdas/session/src/main/java/uk/gov/di/ipv/cri/address/api/service/SessionRequestService.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AccessTokenService.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifier.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AccessTokenServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifierTest.java
* Validate that the issuer and subject for the JWT in the token request match the client id
* Update expected audience and credential issuer URIs in parameter store
* !Ref the KMS signing key directly
* Remove the IssueCredentialFunctionRole and map the policy on the IsseeCredentialFunction directly - tidying up KMS sign and SSM policies
To fix integration with IPV Core in staging
This has been tested on a dev stack, where a complete journey can be completed.
- [KBV-360](https://govukverify.atlassian.net/browse/KBV-360)
> KBV-360  validate client

- infrastructure/lambda/template.yaml
* !Ref the AddressCriVcSigningKey directly in SAM template, as this yields the key id
* Update expected audience and credential issuer URIs in parameter store
* Remove hard-coded KMS key ids
- [KBV-360](https://govukverify.atlassian.net/browse/KBV-360)
> KBV-360 !Ref the AddressCriVcSigningKey directly in SAM template

- infrastructure/lambda/template.yaml
* Remove the IssueCredentialFunctionRole and map the policy on the IssueCredentialFunction directly
* tidy up KMS sign and SSM policies
- [KBV-360](https://govukverify.atlassian.net/browse/KBV-360)
> KBV-360 Inline the IssueCredentialFunctionRole

- infrastructure/lambda/template.yaml
- lambdas/address/build.gradle
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
This PR is a copy of @techaman-m 's PR https://github.com/alphagov/di-ipv-cri-address-api/pull/109 - but includes the new sub-modules 😱.
(I learned a heap about git sub-modules here)
Please see his PR for any comments and context, as I've just re-implemented his code.
- [KBV-342](https://govukverify.atlassian.net/browse/KBV-342)
> KBV-342 Send Address CRI audit events to TxMA

- infrastructure/lambda/template.yaml
Use the dev platform supplied  [checkov checks](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3062726680/How+to+prepare+AWS+accounts+for+containing+SAM+deployment+pipelines#Checkov-hook-(template-analysis)) to validate that our infra is deployed and runs with some accumulated best practice.
1. Add a new Symmetric KMS key to protect:
* DynamoDB tables
* Api Access LogGroup
2. Enable point-in-time recovery on DDB tables.
3. Disable checks for:
* CKV_AWS_173 - Check encryption settings for Lambda environmental variable
* CKV_AWS_116 - Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ)
* CKV_AWS_120 - Ensure API Gateway caching is enabled
* CKV_AWS_7 - Ensure rotation for customer created CMKs is enabled (bypassed for our asymmetric signing and decryption …
> KBV-394 Checkov secure infra hook

- infrastructure/lambda/template.yaml
Reverts alphagov/di-ipv-cri-address-api#117
There is an issue with encrypting the DDB, so reverting until I can figure this out.
> Revert "KBV-394 Checkov secure infra hook"

- README.md
Check the pipelines work, and if so, have a previous deploy to roll back to.
> BAU A simple change to test the pipeline through to integration

- infrastructure/lambda/template.yaml
IPV Core has updated its domains in all environments. Update jwt issuer and redirect url parameters to match required new values.
> BAU: Update config for connection to core

- infrastructure/lambda/template.yaml
Allow staging and integration to be both stub and prod-like environments.
Staging and Integration should end up with SSM parameters for both the `ipv-core` and `ipv-core-stub` client ids.
- [KBV-395](https://govukverify.atlassian.net/browse/KBV-395)
> KBV-395 Allow staging and integration to be both stub and prod-like environments

- infrastructure/lambda/template.yaml
Output the Api Gateway ID
Created output and export for the apigateway id only.
Required to create DNS aliases and frontend config
- [KBV-428](https://govukverify.atlassian.net/browse/KBV-428)
> KBV-428: add AddressApiGatewayId output

- infrastructure/lambda/template.yaml
Fix missing policy to read a vc issuer SSM param
> FIX Read cv issuer param

- infrastructure/lambda/template.yaml
Use DNS issuer and audience for address CRI
> KBV-570 Use DNS issuer and audience for address CRI

- infrastructure/lambda/template.yaml
Unbreak the build as we were trying to replace an SSM param value using a new SSM param resource
> BAU Restore auth alg per client

- infrastructure/lambda/template.yaml
Add `ipv-core-stub-pre-prod` client to address prod.
This gets the address cri working from our pre-prod stub. The config is similar to KBV so the param values should be correct.
> KBV-26 Add ipv-core-stub-pre-prod client to address prod

- infrastructure/lambda/template.yaml
Add provisioned concurrency in production to all lambdas.
This was tested against a dev stack in our cri dev environment, by using the `CreateDevResources` condition instead.
- [KBV-613](https://govukverify.atlassian.net/browse/KBV-613)
> KBV-613 Add provisioned concurrency in prod

- infrastructure/lambda/template.yaml
Output the stack name from the API template, so that it can be used in the acceptance test CodeBuild script.
- [KBV-672](https://govukverify.atlassian.net/browse/KBV-672)
> BAU Output the stack name

- .github/workflows/post-merge-deploy-to-dev.yml
Removed duplicated code signing step
The duplicated step was causing the deployment to fail
- [KBV-801](https://govukverify.atlassian.net/browse/KBV-801)
None
> KBV-801 fix dev deployment workflow

- build.gradle
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lib/build.gradle
Add X-Ray tracing to lambdas & Ordnance Survey API call.
Add XRay `@Tracing` annotation to lambdas and postcode lookup service.
Allow metrics on Ordnance Survey API calls.
- [OJ-879](https://govukverify.atlassian.net/browse/OJ-879)
Unable to test on a dev stack due to code signing issues on dev environment
> OJ-879 X-Ray tracing to lambdas & Ordnance Survey API call

- .gitmodules
- build.gradle
- lambdas/address/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/postcode-lookup/build.gradle
- lib/build.gradle
Remove common cri lib git module
Use common cri lib from safelisted artifactory
- [OJ-931](https://govukverify.atlassian.net/browse/OJ-931)
> OJ-931 - Use cri-common-libs in Address API

- infrastructure/lambda/template.yaml
We don't need to rate limit or use API keys for Dev stack
> BAU: Stop using rate limits and api keys on Dev stack

- integration-tests/build.gradle
- integration-tests/src/test/java/gov/uk/address/api/runners/RunCucumberTest.java
- integration-tests/src/test/java/gov/uk/address/api/stepDefinitions/AddressApiHappyPath.java
- integration-tests/src/test/java/gov/uk/address/api/util/PostcodeLookupResponse.java
- integration-tests/src/test/resources/features/AddressAPIHappyPath.feature
- settings.gradle
Added new Address API pre-merge happy path scenario
- [OJ-966](https://govukverify.atlassian.net/browse/OJ-966)
> OJ-966: Address API pre-merge happy path

- deploy.sh
- infrastructure/lambda/template.yaml
- lambdas/address/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/postcode-lookup/build.gradle
Reverts alphagov/di-ipv-cri-address-api#194
> Revert "OJ-958: removed the zip build process for lambdas"

- deploy.sh
- infrastructure/lambda/template.yaml
- lambdas/address/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/postcode-lookup/build.gradle
Reverts alphagov/di-ipv-cri-address-api#195
> Revert "Revert "OJ-958: removed the zip build process for lambdas""

- .github/workflows/pre-merge-integration-test.yml
- deploy.sh
> BAU fix deploy

- .github/workflows/pre-merge-checks.yml
- .gitignore
- .pre-commit-config.yaml
- lambdas/get-addresses/.eslintrc.js
- lambdas/get-addresses/.prettierrc.js
- lambdas/get-addresses/events/event.json
- lambdas/get-addresses/jest.config.ts
- lambdas/get-addresses/package-lock.json
- lambdas/get-addresses/package.json
- lambdas/get-addresses/src/app.ts
- lambdas/get-addresses/tests/unit/test-handler.test.ts
- lambdas/get-addresses/tsconfig.json
As part of the setup for the Node Lambda, I've gone ahead and tweaked the linter and made some adjustments to how it works.
To unify our code across the lambdas when working with NodeJS.
- [OJ-958](https://govukverify.atlassian.net/browse/OJ-958)
> OJ-958-Config-setup

- build.gradle
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHanderTest.java
- settings.gradle
Log the fact that a session was found in each lambda, which surfaces the `govuk_signin_journey_id`.
Added logging
Record of `govuk_signin_journey_id` in every lambda invocation.
- [OJ-930](https://govukverify.atlassian.net/browse/OJ-930)
> OJ-930 log govuk_signin_journey_id in each lambda request

- README.md
> Update documentatio for new deployment

- lambdas/get-addresses/README.md
> Add Readme for getAddress function

- .github/dependabot.yml
- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/pre-merge-checks.yml
- .github/workflows/pre-merge-integration-test.yml
> BAU update pipeline versions

- integration-tests/src/test/java/gov/uk/address/api/stepDefinitions/AddressApiHappyPath.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/models/Dpa.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/models/Header.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
> fix: ignore unknown new fields coming back from Ordnance Survey

- .github/workflows/pre-merge-integration-test.yml
build: delete pre-merge stack with aws cloudformation delete-stack. This deletes the stack asynchronously.
`sam delete` is timing out deleting stacks in cri-dev.
> BAU build: delete pre-merge stack with aws cloudformation delete-stack

- integration-tests/src/test/java/gov/uk/address/api/stepDefinitions/AddressApiHappyPath.java
- integration-tests/src/test/resources/features/AddressAPIHappyPath.feature
Add premerge acceptance tests to the repo for getAddresses lambda function. 
This will give us great confidence changes to the lambda will continue to work.
> Add premerge integration tests for getAddresses

- .github/workflows/pre-commit.yml
Add precommit GHA
To better detect accidental leaks of secrets
> Add precommit GHA

- .github/workflows/dependabot-pre-merge-integration-test.yml
- .github/workflows/pre-merge-integration-test.yml
- .secrets.baseline
Refactored workflows to allow dependabot to run the automated integration tests in the shared dev environment via a secure process. 
These changes are required so that we can test the dependabot changes pre-merge to main and mitigate bugs in the higher environments.
- [OJ-1022](https://govukverify.atlassian.net/browse/OJ-1022)
> OJ-1022 dependabot integration tests

- .github/dependabot.yml
Add BAU to dependabot commit-message
> BAU-add-bau-to-dependabot-for-java-dependancies

- infrastructure/lambda/template.yaml
- [OJ-1108](https://govukverify.atlassian.net/browse/OJ-1108)
> Change VC expiry time to 6 months

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/pre-merge-integration-test.yml
Workflows have been updated:
* Deprecated GHA actions have been updated to the newer versions.
* setup-sam fix has been applied
Primarily to apply the setup-sam fix so that the workflows are not broken.
(https://github.com/aws/aws-sam-cli/issues/4527)
Secondly in preparation for GitHub to remove the deprecated functionality.
- [OJ-1146](https://govukverify.atlassian.net/browse/OJ-1146)
[OJ-1146]: https://govukverify.atlassian.net/browse/OJ-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1146 workflow deprecations and sam fix

- .github/workflows/pre-merge-integration-test.yml
- infrastructure/lambda/template.yaml
Fix pipeline failures.
Pinned the Gradle version in the GitHub workflow.
To fix failures due to the workflow trying to use the latest version which is incompatible.
- [OJ-1243](https://govukverify.atlassian.net/browse/OJ-1243)
[OJ-1243]: https://govukverify.atlassian.net/browse/OJ-1243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OJ-1243] Fix-issues-with-pipeline-failing-due-to-gradle-versions

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/pre-merge-integration-test.yml
- Updated SAM versions in post merge files
- Pinned Gradle version in post merge files
Fix workflows as failing in Main branch
> Oj 1243 fix issues with pipeline failing due to gradle versions post merge

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/pre-commit.yml
- .github/workflows/pre-merge-integration-test.yml
Pinned python version
To prevent incompatibility issues in the future.
- [OJ-XXXX](https://govukverify.atlassian.net/browse/OJ-1275)
> OJ-1275: Pin software versions in all repos

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
> Revert TS lambdas

- build.gradle
- infrastructure/lambda/template.yaml
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
see: https://github.com/alphagov/di-ipv-cri-lib/pull/208
> OJ1313: use vc expiry release flag

- .github/workflows/pre-merge-integration-test.yml
- integration-tests/src/test/resources/cucumber.properties
Added the code for the cucumber reporting
> Added the changes to include the cucumber reporting

- .github/workflows/pre-commit.yml
- .github/workflows/pre-merge-integration-test.yml
> Added code to allow perms for history

- build.gradle
see: https://github.com/alphagov/di-ipv-cri-lib/pull/247
> OJ-1422: update common lib to 1.5.2

- infrastructure/lambda/template.yaml
`template.yaml` increased rate limit related configs by a factor of 2.
During performance testing, ~90% of tests failed due to rate limit. 
- [OJ-1693](https://govukverify.atlassian.net/browse/OJ-1693)
[OJ-1693]: https://govukverify.atlassian.net/browse/OJ-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1693: Rate limiting

- infrastructure/lambda/template.yaml
Increased rate limits: 
```
ThrottlingRateLimit: 1000
ThrottlingBurstLimit: 2000
```
Performance testing failed
- [OJ-1693](https://govukverify.atlassian.net/browse/OJ-1693)
[OJ-1693]: https://govukverify.atlassian.net/browse/OJ-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1693: Increased rate limit

- .pre-commit-config.yaml
- .secrets.baseline
- infrastructure/lambda/template.yaml
IPS-284 Dynatrace Integration
IPS-284 Dynatrace Integration
- [IPS-284](https://govukverify.atlassian.net/browse/IPS-284)
[IPS-284]: https://govukverify.atlassian.net/browse/IPS-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-284 Dynatrace Integration

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/exceptions/PostcodeLookupTimeoutException.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHanderTest.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
- Added timeout connection to http request
- To resolve https://govukverify.atlassian.net/browse/INCIDEN-665
- [OJ-2292](https://govukverify.atlassian.net/browse/OJ-2292)
[OJ-2292]: https://govukverify.atlassian.net/browse/OJ-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Oj 2292 add timeout to postcode lookup function

- infrastructure/lambda/private-api.yaml
see: https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/279
This is updating Address private-api to keep it up to date
- [OJ-2441](https://govukverify.atlassian.net/browse/OJ-2441)
[OJ-2441]: https://govukverify.atlassian.net/browse/OJ-2441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2441: Added 403 response

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
Minor refactor to postcode error metrics to put it into its own method
Readability.
- [OJ-2647](https://govukverify.atlassian.net/browse/OJ-2647)
[OJ-2647]: https://govukverify.atlassian.net/browse/OJ-2647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2647: Minor refactor to postcode error metrics code

- build.gradle
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/postcode-lookup/build.gradle
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
Upgrade common-lib to 3.0.2
- [OJ-2714](https://govukverify.atlassian.net/browse/OJ-2714)
[OJ-2714]: https://govukverify.atlassian.net/browse/OJ-2714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2714: Upgrade common-lib to 3.0.2

- lambdas/get-addresses/package-lock.json
- lambdas/get-addresses/package.json
Remove esbuild-jest
Unused dependency that has a transitive dependency with a security vulnerability https://github.com/govuk-one-login/ipv-cri-address-api/security/dependabot/22
> Remove esbuild-jest

- doc/api.puml
Added international address routing to plant uml diagram.
Reads:
```
if international_address
if(countryCode is GB,GG.JE,IM)
display UK address screen
else
display international address screen
else
display UK address screen
```
**Screenshot**
- [OJ-2831](https://govukverify.atlassian.net/browse/OJ-2831)
[OJ-2831]: https://govukverify.atlassian.net/browse/OJ-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> doc: add international address flow

- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/InternationalAddressVcTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/states/InternationalAddressStates.java
Added contract test for international addresses
So that we can be sure VCs with international address will be accepted by core
Tested locally with a file provided by core [here](https://gds.slack.com/archives/C04RJGAQ8JZ/p1736165450392379?thread_ts=1733315374.990619&cid=C04RJGAQ8JZ)
- [OJ-2944](https://govukverify.atlassian.net/browse/OJ-2944)
[OJ-2944]: https://govukverify.atlassian.net/browse/OJ-2944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2944: Add contract test for international address

- lambdas/get-addresses/src/services/address-service.ts
- lambdas/get-addresses/tests/unit/services/address-service.test.ts
Increase logging for addresses endpoint
We can't currently track calls to this API using the `govuk_signin_journey_id` which leaves gaps in our observability
- [PYIC-7943](https://govukverify.atlassian.net/browse/PYIC-7943)
[PYIC-7943]: https://govukverify.atlassian.net/browse/PYIC-7943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PYIC-7943: Increase logging for addresses endpoint

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
Stop logging OS API request URL
Because it contains sensitive information
- [OJ-3001](https://govukverify.atlassian.net/browse/OJ-3001)
[OJ-3001]: https://govukverify.atlassian.net/browse/OJ-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3001: Stop logging OS API request URL

- infrastructure/lambda/template.yaml
Reverts govuk-one-login/ipv-cri-address-api#1169
> Revert "OJ-3001: Temporarily lower the secrets manager caching"

- infrastructure/lambda/template.yaml
- lambdas/get-addresses/package-lock.json
- lambdas/get-addresses/package.json
- lambdas/get-addresses/src/get-addresses-handler.ts
- lambdas/get-addresses/src/lib/tracer.ts
- package-lock.json
Add OpenTelemetry to GetAddresses Lambda (Only TS lambda)
Modify Lambda layers in template file so now the TS lambda uses the Node Layer.
This adds instrumentation to GetAddress TS Lambda so that we can see more details traces in dynatrace.
- [OJ-3014](https://govukverify.atlassian.net/browse/OJ-3014)
[OJ-3014]: https://govukverify.atlassian.net/browse/OJ-3014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3014: OpenTelemtry for TS Lambda

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/models/Postcode.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
Some recommendation on this PR https://github.com/govuk-one-login/ipv-cri-address-api/pull/1199
implemented here:
1. Use a model for PostCode 
2. And making ObjectMapper static
> Minor refactoring

- build.gradle
bump cri-lib to 4.2.0
- [OJ-3106](https://govukverify.atlassian.net/browse/OJ-3106)
[OJ-3106]: https://govukverify.atlassian.net/browse/OJ-3106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> deps: bump cri-lib to 4.2.0

- lambdas/pii-redact/src/pii-redact-handler.ts
- step-functions/add-expiry-to-addresses.asl.json
Reverts govuk-one-login/ipv-cri-address-api#1270
> Revert "feat: increase sleep to 10 seconds"

- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
This current PR adds
- JWKS endpoint `/.well-known/jwks.json` 
- Associated alarms definitions for Address CRI
JsonWebKeys5XXApiGwErrorAlarm
JsonWebKeys5XXApiGwErrorAlarm
JsonWebKeys4XXApiGwErrorAlarm
as part of [OJ-2969](https://govukverify.atlassian.net/browse/OJ-2969)
Create a public `/.well-known/jwks.json` endpoint through S3 integration that now exposes a JSON Web Key Sets (JWKS) which contain public encryption key(s) required by core to encrypt JWT Secured Authorization Requests (JAR) request to the Address CRI
`/.well-known/jwks.json` are a standard way of sharing or publishing public keys for API(s) this allow use to align better with established standards see https://github.com/govuk-one-login/architecture/blob/main/adr/0083-publishing-signing-keys-for-vcs.md#json-web-key-sets-jw …
> OJ-2969: Create .well-known/jwks.json for CRI public keys and alarms

- build.gradle
Adds a check for `jacocoTestReport` tasks
Java unit test coverage was not being genarated
> Add task name check
