- deploy.sh
- deploy/api.yaml
- deploy/template.yaml
- doc/api.puml
Reference the openapi yaml file from a local file, rather than s3
Removed the need to place the openapi yaml in s3, we can refer to it locally.
Using an S3 bucket makes more moving parts, and I didn't know how to do this previously - props to @jkunle for figuring this out.
- [KBV-142](https://govukverify.atlassian.net/browse/KBV-142)
> KBV-142 Reference openapi definition from local file

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- README.md
- deploy/template.yaml
Update to enable GitHub actions deployments into the di-ipv-cri-dev AWS account.
* Added GitHub actions workflow for deployment on push to main after PR approval.
* Updated SAM template to include code signing.
To enable automated GitHub actions deployments into the di-ipv-cri-dev AWS account.
- [KBV-177](https://govukverify.atlassian.net/browse/KBV-177)
Required GitHub secrets inside and environment for added security:
| Secret | Description |
| ------ | ----------- |
| AWS_ROLE_ARN | Assumed role IAM ARN |
| AWS_PROFILE_PATH | Parameter Store path to the signing profile versioned ARN |
| AWS_ROLE_SESSION | Assumed Role Session ID
> [KBV-177] GitHub actions sam deploy

- .github/workflows/deploy.yml
- deploy/template.yaml
* Update SSM parameter name to bring into line with naming convention updates.
* Remove erroneous extra region parameter arg from deployment config.
* The parameter name changed due to conventions introduced with the new AWS account.
* The additional arg caused incorrect s3 prefix to be used.
- [KBV-177](https://govukverify.atlassian.net/browse/KBV-177)
None
> KBV-177] Update parameter names and deploy config

- .github/workflows/dev-manual.yml
Updated the dev deployment to use the same secrets and and more in alignment with the dev-platform team
Dev deployment to be manually triggered
The change has been made to allow the dev CD be used for testing the workflow with configuration closer aligned to the platform teams process. There is no requirement to have the dev builds automatically run but may prove useful for testing and debugging the process.
- [KBV-233](https://govukverify.atlassian.net/browse/KBV-233)
None
> KBV-233 update dev deployment to be manual

- .github/workflows/post-merge-deploy-to-dev.yml
After merge to main, deploy to the `di-ipv-cri-address-api-dev` CloudFormation stack on our dev account.
This is the API that the PaaS frontend app `dev-di-ipv-cri-address-front` is configured to use. 
* Renamed GHA file to be more descriptive
* GHA is triggered on merge to main
* sam validate happens before gradle build
* remove some refs to `--config-env` which only apply if we're using a samconfig.toml file
- [KBV-270](https://govukverify.atlassian.net/browse/KBV-270)
> KBV-270 Deploy to dev post-merge

- deploy/template.yaml
- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AccessTokenHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/exception/AccessTokenRequestException.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/persistence/item/AddressSessionItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressSessionService.java
When the item is retrieved through the Global Index using the authorizationCode, the `redirectUri` field is blank. This results in a Null pointer Exception
Added `redirectUri` as a Non Key Projection to the authorizationCode-index global index
- The AddressSessionService requires more test coverage this would be added as a subsequent PR
> BAU: Fix Non key value retrieval for redirectUri

- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressSessionService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressSessionServiceTest.java
Added more test coverage to handle access token operation
A major refactoring on KBV-146 was to move validation logic from the handler into the AddressSessionService
However, some of the methods in the service do not have direct test coverage this PR add more test coverage
- Still not a 100% but sufficient enough
> BAU: Increasing the coverage for access token operations

- infrastructure/lambda/template.yaml
Update the lambda CodeUri paths in the SAM template
The paths need to change to reflect the new location of the template. Without this change the CD will fail.
- [KBV-286](https://govukverify.atlassian.net/browse/KBV-286)
None
> [KBV-286] fix lambda CodeUri paths in the SAM template

- infrastructure/lambda/template.yaml
Fix incorrect path for Address function
BAU: Template had incorrect parent path for deploying the build artifact for the Address Function
> Updated template.yaml

- lib/src/main/java/uk/gov/di/ipv/cri/address/library/helpers/ClassToMapConverter.java
The ClassMapConverter was made generic and tests passed, but real world tests failed.
This was due to the fact it was made more generic, but in doing so, lost some type checking - with the main one being not trying to do any additional checks on the value type if it was null
> Fix ClassMapConverter where value was null

- .github/workflows/post-merge-package-for-build.yml
- README.md
Removed GitHub environment from workflow for staging deployment
GitHub environments and incompatible with the dev platform team's deployment process due to restrictions imposed by AWS.
- [KBV-290](https://govukverify.atlassian.net/browse/KBV-290)
None
> [KBV-290] remove environment from staging

- infrastructure/lambda/api.yaml
- infrastructure/lambda/template.yaml
Protect all resources on the Address CRI API by requiring clients to use an API key. These clients are the Address CRI frontend (currently in PaaS) and the IPV Core (cross-account in AWS).
This PR lands the UsagePlan and creates the keys, but does not require clients to use the keys yet.
Clients will have to supply the api key in the http header `x-api-key`.
The API key values can be found in the AWS Console.
This has been tested on a stack in our cri dev environment.
* Add two api keys for the address cri api gateway - we provision two so we can share the 2nd key if/when required
* Add an API usage plan for our gateway with burst and rate limits
* Add a commented out usage of that api key in our OpenApi definition. This protects the entire API gateway, but its possible to set this …
> KBV-227 Protect Address CRI API with an api key

- infrastructure/lambda/template.yaml
Update the JWT `iss` to `https://dev.core.ipv.account.gov.uk` for the dev environment, and similar for other environments.
This may not be the final issuer url, but I'd like to set the value uniformly across environments for now.
> Update address CRI issuer SSM param across environments

- infrastructure/lambda/template.yaml
This is the first of 2 PR's to fix code-pipeline error
A rename is equivalent to a delete and then an add
This PR is the delete phase, as far as code-pipeline is concerned
there are currently 2 indices,  so once this deployed there wiil be one
i.e token-index is removed
The next PR will add the required access-token-index
> BAU: Remove Global Secondary index

- infrastructure/lambda/template.yaml
This is the 2nd PR, which adds the required access-token-index
See the previous https://github.com/alphagov/di-ipv-cri-address-api/pull/58
> BAU: add accesstoken gsi index

- .github/workflows/post-merge-package-for-build.yml
- infrastructure/lambda/template.yaml
Pipeline failed in build b'cos code signing was left out of this
https://github.com/alphagov/di-ipv-cri-address-api/pull/58
So am redoing it with code-signing applied for build
To the build environment this PR is equivalent to removing the
token-index
> BAU: Remove access-token-index

- infrastructure/lambda/template.yaml
The value of the AddressCriAudience SSM parameter (used by the Session lambda function) is assigned on a per environment basis.
To align with the current credential issuer configuration in di-ipv-config
- [KBV-305](https://govukverify.atlassian.net/browse/KBV-305)
> KBV-305 - Make AddressCriAudience param value env specific

- lambdas/session/src/main/java/uk/gov/di/ipv/cri/address/api/handler/SessionHandler.java
- lambdas/session/src/test/java/uk/gov/di/ipv/cri/address/api/handler/SessionHandlerTest.java
Return `state` and `redirect_uri` in session API response so that the frontend can save these values to send back in the auth code redirect.
This is now necessary as the Authorization JWT request now contains these values in the Authorization JAR, rather than as http request params.
- [KBV-305](https://govukverify.atlassian.net/browse/KBV-305)
> KBV-305 Return state and redirect_uri in session API response

- lib/src/main/java/uk/gov/di/ipv/cri/address/library/models/CanonicalAddress.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/VerifiableCredentialService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/VerifiableCredentialServiceTest.java
Use custom parser for converting Canonical Address to a JSONObject (to handle optionals and date formatting)
- Test re-enabled
- Added a "toJSONObject" method on the Canonical Address to ensure correct serialization
The Nimbus library masks away its own serialization, which is based on Java 7 types, due to the fact is utilises JSON Compact etc - therefore it doesn't support Optional, nor does it obey Json Attributes when serializing.
- [KBV-349](https://govukverify.atlassian.net/browse/KBV-349)
> [KBV-349] Fix Address VC Handling of Canonical Address

- infrastructure/lambda/template.yaml
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifier.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifierTest.java
Add Auth JAR Decryption KMS key per account. Wire in the KMS key id to decrypt policies.
Also add an SSM param at `/${AWS::StackName}/clients/ipv-core-stub/jwtAuthentication/publicSigningJwkBase64` that supports using a public key JWK for sig verification.
Switched from one hardcoded KMS key id configured for the dev account to a provisioned KSM decrypt key per stack on an account.
- [KBV-308](https://govukverify.atlassian.net/browse/KBV-308)
> KBV-308 Decryption KMS key per account

- infrastructure/lambda/template.yaml
* Add IPV-Core as a client to the Staging Address CRI
* Add additional expected config for integration and staging, accepting that these values may change
Note that clients are distinctly represented by their path in SSM parameter store e.g.
````
/${AWS::StackName}/clients/ipv-core/jwtAuthentication/audience
/${AWS::StackName}/clients/ipv-core-stub/jwtAuthentication/audience
````
This will allow us to accept more than one IPV Core client to support key rotation done by IPV Core, so they could start sending requests with a different client id - which we’d have configured ahead of time.
The `clients/{client-id}/`  portion of the SSM parameter would have to be new. The `1` in the YAML name is a just a way to support this idea that there may be multiple clients from the same issuer.
Allow IPV …
> KBV-360 Add IPV-Core as a client for staging

- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/domain/VerifiableCredentialConstants.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/exception/CredentialRequestException.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/helpers/KMSSignerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/helpers/SignClaimSetJwtTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/helpers/fixtures/TestFixtures.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialServiceTest.java
Move classes needed for the issue endpoint from lib into
the verifiable credential module in other to make lib more self contained
> BAU: Refactor credential issue endpoint artefacts

- README.md
- infrastructure/lambda/template.yaml
- lambdas/jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/EnvironmentService.java
- lambdas/jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetHandler.java
- lambdas/jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetService.java
- lambdas/jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/KMSService.java
- lambdas/jwkset/src/test/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetHandlerTest.java
- lambdas/jwkset/src/test/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetServiceTest.java
Update JWKSetFunction to filter on KMS keys deployed in the same stack.
This is necessary to avoid IAM permission errors on reading KMS public keys outside the JWKSetFunction's owning stack.
* Add an extra "stack name" tag on the KMS keys
* Evaluate that the stack name tag matches the JWKSetFunction's stack name
* Add a README.md section to explain how to configure KMS keys
* Move a bunch of methods out of the function handler and into a new JWKSetService
The jwkset url wasn't working, as the fn was trying to read the public keys outside this stack, for which there was no IAM policy.
- [KBV-363](https://govukverify.atlassian.net/browse/KBV-363)
> KBV-363 Update JWKSetFunction to filter on KMS keys deployed in the same stack

- infrastructure/lambda/template.yaml
PR 1 of 4 to recreate secondary indexes on the Session Table to handle correct projections
> [KBV-358] Remove secondary indexes on the session table

- infrastructure/lambda/template.yaml
PR 2 of 4 to recreate secondary indexes on the Session Table to handle correct projections
> [KBV-358] Remove secondary index on authorization code on session table

- infrastructure/lambda/template.yaml
PR 3 of 4 to recreate secondary indexes on the Session Table to handle correct projections
> [KBV-358] Re-add secondary index for access token on session table

- infrastructure/lambda/template.yaml
PR 4 of 4 to recreate secondary indexes on the Session Table to handle correct projections
> [KBV-358] Re-add secondary index for authorization code on session table

- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/SessionService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/SessionServiceTest.java
SessionService updated to return all fields of the SessionItem when retrieving by auth code
The current projection on the auth code index contains insufficient to update the SessionItem after it has been retrieved.
- [KBV-358](https://govukverify.atlassian.net/browse/KBV-358)
> KBV-358 - Return complete session item when retrieving by auth code

- infrastructure/lambda/template.yaml
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifier.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/JWTVerifierTest.java
The EC signatures produced by AWS KMS are in DER format. The Nimbus lib we're using to verify the signatures needs them in concat format.
This is a [copy of the code passport-back](https://github.com/alphagov/di-ipv-cri-uk-passport-back/pull/105/commits/8573927bad3deb68f57bece09e1fc32753222d8e) uses to transcode a DER format signature to concat format.
👉 Also.. fix the redirect uri to a form that IPV Core expects.
- [KBV-360](https://govukverify.atlassian.net/browse/KBV-360)
> KBV-360 transcode KMS DER sigs to concat format

- infrastructure/lambda/template.yaml
The Authorization Jar validation is breaking with journeys from IPV Core Stub.
Match the expected audience and issuer from IPV Core Stub, in order to pass validation.
I've applied these values to the SSM parameter store on address api in dev, and this allows a complete Address CRI journey.
> BAU: Update expected audience and issuer from IPV Core Stub

- infrastructure/lambda/api.yaml
API gateway intermittently fails validation on the `/session` request when the [JWE](https://datatracker.ietf.org/doc/html/rfc7516) sent in the Authz JAR fails a regex check:
````
(5081812f-4dfc-46a0-9172-c9b813cac751) Request body does not match model schema for content type application/json: [ECMA 262 regex "[a-zA-Z0-9_=]+\.[a-zA-Z0-9_=]+\.[a-zA-Z0-9_\-\+\/=]+" does not match input string "eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.FDFE5bZ74Byg1AhuQNDNM9X7INyt2tJNJHhijvJtGNTB-GGtCSxnOcUwqlJNMKImd2BKl813P2F58aU17ljOzM0-fXqb8M3_gWxFg8ZmVMYNo2FHbcN7ptoSg3A2WaWAEYSiUdUpJzU2_Uk-91DZwjpsAZUj0BCTemiSwKZOpW9kQoPPEgS27alS_Ia5RWkr8w9C_EUgFpdadUkP2xWP76j7uvRX_fnlGMwfxkPkhjlSIMHlZ-taL_FxMTiezcn7urcUyQAqma_MuN3NgG50qAnjbn2oVLsYJ4wEUfDFibAQMG4EUBvwQ6LDEsIkXALsCtkC2mkE3OFnUxXpS …
```
> BAU Remove regex on auth jar

- infrastructure/lambda/template.yaml
We have propagated KMS keys for VC signing and Auth Jar decryption, created by the [core-infrastrucure stack](https://github.com/alphagov/di-ipv-cri-common-infrastructure/tree/main/core), all the way to the Address CRI integration environment.
Remove the KMS enc and sig keys created in the API stack and ref the imported key ids/arns from core-infrastructure stack
This means we get to use long-lived KMS keys set per environment - even in dev!
✅ This works in an end-to-end journey on a dev stack.
- [KBV-395](https://govukverify.atlassian.net/browse/KBV-395)
> KBV-395 Use KMS keys from core-infrastructure stack

- infrastructure/lambda/template.yaml
Add new PersonIdentity dynamo db table
( please note this will be moved to the common infrastructure repo in the future )
To enable the user's PII to be persisted
- [KBV-377](https://govukverify.atlassian.net/browse/KBV-377)
> KBV-377 - add PersonIdentity dynamo db table

- infrastructure/lambda/template.yaml
Allow IPV Core Stub to be a client to Address CRI in staging and integration.
The core stub will use the `ipv-core-stub` client id, so that address CRI can accept both IPV Core and IPV Core stub as cleints in an environment.
Another PR will set the config needed for IPV Core Stub to connect to address cri in staging and integration.
So CRI team can test Address CRI in integration without a dependency on IPV Core.
- [KBV-395](https://govukverify.atlassian.net/browse/KBV-395)
> Connect Core stub toAddress CRI in staging and int

- infrastructure/lambda/template.yaml
Add the correct IPV Core public JWK so we can verify the Auth JAR came from that environment.
This was nicked from newly-created passport CRI config.
- [KBV-395](https://govukverify.atlassian.net/browse/KBV-XXX)
> KBV-395 IPV Core public JWK for verifying Auth JAR

- infrastructure/lambda/template.yaml
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- Modify AuditEventTypes -> AuditEventType
- Use new simplified events
- Added SQS Event Prefix parameter
The SQS Event System was very tailored to each service, despite being in the common libraries - this meant keeping a list of enums for all CRIs within the common library - this would not be maintainable in the long run.
Considering these all consisted of the CRI name as a prefix, we decided to move this prefix to an environment variable and prepend it to the event
- [KBV-517](https://govukverify.atlassian.net/browse/KBV-517)
- SQS_AUDIT_EVENT_PREFIX (Required, not empty)
> [KBV-517] Amend Audit Service and Calls

- doc/api.puml
- infrastructure/lambda/api.yaml
- infrastructure/lambda/template.yaml
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialServiceTest.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHanderTest.java
- settings.gradle
- Update to move the authorization code response away from the /address endpoint and utilised /authorization common lambda
- Updated documentation
- Updated references to common submodules
All CRIs now use a series of common lambdas and endpoints.
The Address CRI was returning the authorization code as part of the response to /address, which does not match the new patterns, nor the correct OAuth flow
- [KBV-506](https://govukverify.atlassian.net/browse/KBV-506)
> [KBV-506] - Refactor Address CRI to use new /authorization endpoint for returning authorization code

- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
Updated various methods to not refer to the address specific ConfigurationService methods
So the address specific ConfigurationService methods can be removed.
> BAU - update to use latest common ConfigurationService

- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lambdas/postcode-lookup/build.gradle
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHanderTest.java
- Updated Issue Credential Handler to correctly sent 403 access denied if items have expired
- Updated all CRI specific lambdas to send errors using the "IPV-Core" method
In order to align with [RFC 6749 - The OAuth 2.0 Authorization Framework](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2) , we need to ensure when authorization codes are created, they have an expiry time set.
As per the RFC (above), this expiry time should have a maximum recommended TTL of 10 minutes.
Authorization codes must only be used once.
Once successfully changed for a bearer token, the authorization code must be expired.
- [KBV-559](https://govukverify.atlassian.net/browse/KBV-559)
- [RFC 6749 - The OAuth 2.0 Authorization Framework](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2)
> [BAU] Update to the "Core" way of passing errors back

- infrastructure/lambda/template.yaml
Allow the AddressFunction lambda to read the vc issuer SSM param.
This param is also read by the IssueCredentialFunction but that allows read access to a wildcard of params, which will include the param in question.
> FIX Read cv issuer param

- infrastructure/lambda/template.yaml
The address CRI template has been updated to run the lambda inside the VPC as per Fraud and KBV
This brings Address into line with Fraud and KBV deployments which simplifies the deployment process and enhances security
- [KBV-589](https://govukverify.atlassian.net/browse/KBV-589)
None
> [KBV-589] run address CRI inside VPC

- infrastructure/lambda/template.yaml
* [set env var POWERTOOLS_METRICS_NAMESPACE globally for lambdas](https://github.com/alphagov/di-ipv-cri-address-api/commit/9a37b26e68713033560ec24766eb1db5eac81522)
* [set source vpc endpoint id from a stack export, except for dev 😬](https://github.com/alphagov/di-ipv-cri-address-api/commit/5c884dc13cff3607ae5e01c25ea441dace9aff21)
* [set session and jwt ttl to 2 hrs, and set jwt sig alg to ES256 globally](https://github.com/alphagov/di-ipv-cri-address-api/commit/9c842e8377ee3c29c2d26b91f91700eabe089eb3)
* [normalise expected aud from core stub to use dns uris](https://github.com/alphagov/di-ipv-cri-address-api/commit/e77d94a831456c1a569e7092ecf8a8f51d709bb5)
* [set DataTraceEnabled to false for prod envs to not accidentally leak PII in API execution …
> KBV-570 VPC endpoint ids from stack export

- infrastructure/lambda/template.yaml
Send lambda and APIGW log events to a subscription filter which lands log events in splunk
- [KBV-618](https://govukverify.atlassian.net/browse/KBV-618)
> [KBV-618] Send address log events to splunk

- infrastructure/lambda/template.yaml
Send lambda and APIGW log events to a subscription filter which lands log events in splunk
- [KBV-618](https://govukverify.atlassian.net/browse/KBV-618)
> KBV-618 Update config for address log events to splunk

- infrastructure/lambda/template.yaml
Removed JWKSetFunctionLogsSubscriptionFilter
There is no log group for it so causes the deployment to fail
- [KBV-618](https://govukverify.atlassian.net/browse/KBV-618)
> [KBV-618] Remove JWKSetFunctionLogsSubscriptionFilter

- infrastructure/lambda/template.yaml
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialServiceTest.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHanderTest.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
- Updated to the latest versions of `common-lib` and `common-lambdas`
- The postcode lookup lambda function now sends the REQUEST_SENT audit event
- The address lambda function no longer sends the REQUEST_SENT audit event
- The `user` object has been added to all audit events sent by the address CRI
The TxMA team have requested for more data to be provided with the audit events
- [KBV-622](https://govukverify.atlassian.net/browse/KBV-622)
> KBV-622 - Add audit event metadata

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
Conditional provisioned concurrency and alias added to template
Api configurations updated to use alias
To enable provisioned concurrency in production
- [KBV-619](https://govukverify.atlassian.net/browse/KBV-619)
This has been tested in the new address dev account with provisioned concurrency set to 1 and set to 0 to test both both production and non production deployments.
> KBV-619 add provisioned concurrency

- infrastructure/lambda/template.yaml
Changes made to function references to include alias
The deployment fails on the function permissions when the alias is referenced. Adding the .Alias allows for both provisioned and non provisioned deployments
- [KBV-619](https://govukverify.atlassian.net/browse/KBV-619)
Deployment promotion beyond build is disabled
> KBV-619 fix aliased function permissions

- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
Use the new `DevOnlyAddressApi` APIGW as a REGIONAL instead of PRIVATE API for dev only. This is so that we can reach this API from localhost.
Also remove the OpenAPI security scheme requiring an API key from dev only. We must put this back when each CRI has is own dev stack and the shared API keys from the core stack are available.
This has been tested end-to-end on a dev stack.
* [Add a regional APIGW to represent the private APIGW for dev only](https://github.com/alphagov/di-ipv-cri-address-api/commit/96e2d765cfc36ee6a49219258ee1fcdaaa1f67d7)
* [Remove the OpenAPI security scheme in dev only](https://github.com/alphagov/di-ipv-cri-address-api/commit/aeee6f79f0558ad0c19827a9e953474fb43d790f)
> KBV-689 Allow APIs to be reached from dev

- infrastructure/lambda/template.yaml
Use [arm64 for better performance](https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/), and shift to more memory in higher environments.
KBV CRI has already  done it: https://github.com/alphagov/di-ipv-cri-kbv-api/pull/144/files
> BAU Use ARM64 and change memory size per env

- .github/workflows/post-merge-package-for-build.yml
The test image included in the push to build has been removed.
The acceptance test image is now being pushed from a different repository and workflow. The test image included in the push to build is no longer required and breaks the deployment so needs to be removed.
- [KBV-778](https://govukverify.atlassian.net/browse/KBV-778)
None
> KBV-778 remove test image push from GH workflows

- infrastructure/lambda/template.yaml
Added missing log group declarations
A new non dev deployment fails because the log groups do not exist and the template does not include the declarations.
- [KBV-807](https://govukverify.atlassian.net/browse/KBV-807)
This affects new clean non dev deployments only. The retention times may need adjustment.
> KBV-807 Add missing log group declarations

- infrastructure/lambda/template.yaml
The log groups have been renamed
These changes have been made to work around conflicts log group names with @clickopsed" log groups which is preventing the deployments downstream of build. 
- [OJ-822](https://govukverify.atlassian.net/browse/OJ-822)
Log group names can be reverted if required in a subsequent PR after existing log groups have been deleted or otherhow renamed
PLEASE DO NOT MERGE!
> OJ-822 rename log groups

- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
- lib/src/main/resources/log4j2.xml
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
Added a utility method to addressService (setAddressValidity) to link validFrom in a CURRENT address with validUntil in a PREVIOUS address.
After this change AddressAPI will be limited to a max of two address, as validFrom is only set in CURRENT addresses.
ValidUntil will also appear in any PREVIOUS address in the VerifiableCredential, as the field is no longer null.
Additional validation of single address and address pairs.
Specific validation of address dates in addresses.
The setAddressValidity will only link a CURRENT and PREVIOUS address. If a PREVIOUS address with a non null validUntil is found it will not link the dates and throw an AddressProcessingException.
Internally setAddressValidity will use validFrom non-null and validUtil null as sole meaning of a CURRENT address and keeps …
> KBV-771 Link validUntil in a PREVIOUS address to validFrom in a CURRENT address

- infrastructure/lambda/template.yaml
Restore previous log groups configuration
Log groups configuration was not fully configured and logs written to old groups so temporarily restore old groups to ship logs to splunk. New updated log groups need to be enabled for deployment to a clean account but for existing accounts will need importing. 
- [OJ-822](https://govukverify.atlassian.net/browse/OJ-822)
Commented blocks left in which will need importing at a later date
> OJ-822-restore-log-groups

- infrastructure/lambda/private-api.yaml
Check that at least one address is sent in the `/PUT address` method.
Extra APIGW validation on address array
We were getting lambda errors trying to marshall an empty array or string to a `CanonicalAddress[]`. The APIGW should validate these cases, and return a 4xx to the client.
`minItems` is part of the [JSON validation schema](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-minitems), and supported by OpenAPI 3.
> BAU Check that at least one address is sent in the /PUT address method

- settings.gradle
- Removed `common-lib` from `settings.gradle`
- The common-lib git submodule has been removed & the include was redundant
- [OJ-931](https://govukverify.atlassian.net/browse/OJ-931)
> OJ-931 - remove redundant include for common-lib

- infrastructure/lambda/template.yaml
Add both old non python and new python subscription filters for splunk
Requirement to use the new python subscription filters but to keep the old filters to ensure no logs get lost
- [OJ-985](https://govukverify.atlassian.net/browse/OJ-985)
> OJ-985 update logging subscription filters

- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/pre-merge-checks.yml
- .github/workflows/pre-merge-deploy-to-poc.yml
- .github/workflows/pre-merge-integration-test.yml
- .gitmodules
- build.gradle
- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- settings.gradle
- `common-lambdas` submodule removed
- All github workflows updated to no longer checkout git submodules
- Update to version 1.1.3 of cri-common-lib
- `private-api.yaml` / `public-api.yaml` updated to refer to the new common lambda functions
- All common resources removed from `template.yaml`
- `VerifiableCredentialService` updated to use the common `verifiableCredentialKmsSigningKeyId` SSM parameter
- To enable the transition to the new common CRI framework
- [OJ-968](https://govukverify.atlassian.net/browse/OJ-968)
> OJ-968 use common cri stack

- deploy.sh
- infrastructure/lambda/template.yaml
- lambdas/address/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/postcode-lookup/build.gradle
As per discussion we should not be using the logic to zip the `CodeUri` parameter for lambdas in the `template.yaml` while using AWS SAM 
`CodeUri: ../../lambdas/postcode-lookup`
`CodeUri: ../../lambdas/postcode-lookup/build/distributions/postcode-lookup.zip` and associated `build.gradle` file in each Lambda.
The `deploy.sh` file has also been changed to stop using the `template.yaml` file during deployment, accommodate the common-lambdas and drop the`./gradlew` command.
> OJ-958: removed the zip build process for lambdas

- .github/workflows/pre-merge-checks.yml
- .pre-commit-config.yaml
Added github actions to lint and run the tests of the nodelambda functions.
It would be cool if we got around to use precommit in our github actions to run all our checks.
Runs linter and tests when we create a PR.
- [OJ-958](https://govukverify.atlassian.net/browse/OJ-958)
> Add github actions for tests and linting

- build.gradle
As a consequence to
https://github.com/alphagov/di-ipv-config/pull/958
https://github.com/alphagov/di-ipv-stubs/pull/160
Stub are now verifiying the JWT from the VC
There is the need to verify that the JWT produce is coming from the expected party
> OJ-990: Use VC sign concat format

- infrastructure/lambda/template.yaml
Add CloudWatch alarms for Address CRI API that will send events to an SNS topic already configured in core-infrastructure.
See similar for KBV here: https://github.com/alphagov/di-ipv-cri-kbv-api/pull/187
Required for production readiness.
- [OJ-1008](https://govukverify.atlassian.net/browse/OJ-1008)
> OJ-1008 feat: add CloudWatch alarms that report to the core infra SNS topic

- infrastructure/lambda/template.yaml
For 5xx and 4x errors, use the sum of errors across the public and private API gateways.
Previously we used the sum of the API stage, and this didn't seem to work.
The sum expression `e1` is the only metric with `ReturnData: true` so this is the single metric that makes up the alarm.
> sum apigw errors across public and private gateways

- infrastructure/lambda/template.yaml
- Removed old log group subscription filters
- At the request of @instantiator 
- [OJ-1015](https://govukverify.atlassian.net/browse/OJ-1015)
> OJ-1015 - remove old log group subscription filters

- infrastructure/lambda/template.yaml
- lambdas/get-addresses/package-lock.json
- lambdas/get-addresses/package.json
- lambdas/get-addresses/src/app.ts
- lambdas/get-addresses/src/config.ts
- lambdas/get-addresses/src/lib/param-store-client.ts
- lambdas/get-addresses/src/services/address-service.ts
- lambdas/get-addresses/src/services/config-service.ts
- lambdas/get-addresses/src/types/config.ts
- lambdas/get-addresses/tests/unit/app.test.ts
- lambdas/get-addresses/tests/unit/services/config-service.test.ts
- lambdas/get-addresses/tsconfig.json
Use paramstore for the table name rather than a config file.
We should use Param store when using configuration variables like table names. This will allow us to change it via infrastructure if needed.
- [OJ-992](https://govukverify.atlassian.net/browse/OJ-992)
> OJ-992-use-param-store

- build.gradle
- infrastructure/lambda/template.yaml
- integration-tests/src/test/java/gov/uk/address/api/stepDefinitions/AddressApiHappyPath.java
- integration-tests/src/test/resources/features/AddressAPIHappyPath.feature
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/domain/VerifiableCredentialConstants.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialServiceTest.java
- Updated the VC JWT time-to-live assignment
- Updated to the latest version of cri-common-lib
- Removed redundant constants from the VerifiableCredentialConstants class
- Updated VerifiableCredentialService to use the new common VerifiableCredentialClaimsSetBuilder class
- There is a future requirement to change the VC JWT time-to-live to 6 months. Now both the ttl and ttl unit can be specified e.g. 6 MONTHS
- There is unnecessary duplication of the logic to create the VC claims between the address, kbv & fraud CRIs
- [OJ-975](https://govukverify.atlassian.net/browse/OJ-975)
> OJ-975 - Make VC JWT expiry more flexible

- .github/dependabot.yml
- .github/workflows/dependabot-pr-check-yml
- .github/workflows/pre-commit.yml
- .github/workflows/pre-merge-integration-test.yml
- .secrets.baseline
* Added dependabot PR check workflow that triggers the integration tests workflow
* Updated the dependabot configuration to include gradle and GHA dependencies 
These changes are needed now that GitHub have tightened security that by default prevents secrets access from a fork which is effectively the process that dependabot uses.
The gradle and GHA changes allow improved visibility of updates and the option to merge PR's with updates.
(https://github.com/dependabot/dependabot-core/issues/3253)
(https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
- [OJ-1022](https://govukverify.atlassian.net/browse/OJ-1022)
> OJ-1022 Updates for dependabot

- .github/workflows/dependabot-pre-merge-integration-test.yml
Removed the @main version from the referenced workflow.
Versions are not allowed on local workflow calls.
- [OJ-1022](https://govukverify.atlassian.net/browse/OJ-1022)
> OJ-1022 remove version from referenced workflow

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- Removed unnecessary ./gradlew build command from post-merge GHA workflows
- It is not necessary to manually invoke gradle build as the cide compilation and test execution is handled by sam build
> BAU - GHA - remove unnecessary build step from post-merge workflows

- integration-tests/src/test/java/gov/uk/address/api/runners/RunCucumberTest.java
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- integration-tests/src/test/resources/features/InvalidPostcodeTest.feature
We have added an invalid postcode API test
We did not have an invalid postcode API test before
- [OJ-1110](https://govukverify.atlassian.net/browse/OJ-1110)
> OJ-1110: add invalid postcode test

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- Updated the IssueCredentialHandler class to send the END audit event
- As requested by the txma team
- [OJ-959](https://govukverify.atlassian.net/browse/OJ-959)
> OJ-959 - send IPV_ADDRESS_CRI_END audit event

- README.md
Local lambdas testing was removed sometime ago
see: https://github.com/alphagov/di-ipv-cri-address-api/pull/123
> BAU: Update readme removed local testing

- README.md
- deploy.sh
This PR makes `deploy.sh` more configurable. If the need arises to work on an alternate common-stack. i.e one that has slightly different configuration to `address-common-cri-api-local` then you can specify yours as follows:
`gds aws di-ipv-cri-dev -- ./deploy.sh STACKNAME YOUR-COMMON-STACKNAME`
STACKNAME is your own stack address-cri stack that you have deployed to shared dev
YOUR-COMMON-STACKNAME is your own address common cri api-that your have deployed to shared, configured to your needs.
> BAU: Parameterise deploy.sh

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
Restore previous Java lambdas, to unblock the Core E2E and DI E2E tests
> Revert "feat: Switch to using TypeScript common lambdas"

- build.gradle
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
Use the Redaction deserialiser in common-lib
[A redaction deserializer was added to common-lib we can use this to strip possible PII](https://github.com/alphagov/di-ipv-cri-lib/pull/201)
- [OJ-1305](https://govukverify.atlassian.net/browse/OJ-1305)
[OJ-1305]: https://govukverify.atlassian.net/browse/OJ-1305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1305: Use redaction deserializer in Address-cri

- README.md
Facilitate the ability to run the command https://github.com/alphagov/di-ipv-cri-kbv-api#run-integration-tests by changing IPV_CORE_STUB_URL to point to the new aws stub url i.e. https://cri.core.build.stubs.account.gov.uk
In moving from PAAS to AWS, new client needed to be created, the current pre-merge test would need to be flexible enough to ensure the stub client Id can be overriding with the expected one.
Work involving moving from PAAS to AWS
- [OJ-1523](https://govukverify.atlassian.net/browse/OJ-1523)
New Env variable DEFAULT_CLIENT_ID 
Updated [README](./blob/main/README.md) 
`ENVIRONMENT=xxxx STACK_NAME=xxxx IPV_CORE_STUB_CRI_ID=address-cri-dev API_GATEWAY_ID_PRIVATE=xxxx API_GATEWAY_ID_PUBLIC=xxxx IPV_CORE_STUB_BASIC_AUTH_USER=xxxx IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxxx …
> OJ-1523: Ensure integration test works with AWS stub

- .github/workflows/pre-merge-integration-test.yml
Pre-merge-test to use AWS stub instead of PAAS stub
Move away from PAAS to AWS hosting of stub
PAAS would be decommission soon
- [OJ-1533](https://govukverify.atlassian.net/browse/OJ-1533)
Use of DEFAULT_CLIENT_ID to specify stub client id
see: https://github.com/alphagov/di-ipv-cri-address-api/pull/599
[OJ-1533]: https://govukverify.atlassian.net/browse/OJ-1533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1533: Point Pre-merge-test to AWS stub

- build.gradle
- infrastructure/lambda/template.yaml
Use release-flag for `vc-contains-unique-id`  for address-cri implemented by https://github.com/alphagov/di-ipv-cri-lib/pull/244
Added release_flag for vc-contains-unique-id setting it to true In Dev
see: https://github.com/alphagov/digital-identity-architecture/blob/main/adr/0079-unique-identifier-for-verifiable-credential.md#option-6---preferred-optionIn order to be able to distinguish one Verifiable Credential (VC) from another VC it will be necessary for VCs to be able to be uniquely identifiable
- [OJ-1422](https://govukverify.atlassian.net/browse/OJ-1422)
[OJ-1422]: https://govukverify.atlassian.net/browse/OJ-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1422: Add release_flag for vc-contains-unique-id

- infrastructure/lambda/template.yaml
VC Contain Unique Id enabled up to staging 
Included a unique identifier within the jti (JSON Web Token ID) claim representing a VC
Added release_flag for `vc-contains-unique-id` this can be enabled by setting the environment flag to true in the template file. Below all env(s) up to staging have been enabled
```
VcContainsUniqueIdMapping:
Environment:
dev: "true"
build: "true"
staging: "true"
integration: "false"
production: "false"
``` 
- [jti in context of a VC](https://github.com/alphagov/digital-identity-architecture/blob/7c90be0db85a3a3093c766d845d5f278a3d86e16/rfc/0045-claimed-identity-cri.md?plain=1#L217)
- [ADR 0079 Unique identifiers for verifiable credentials](https://github.com/alphagov/digital-identity-architecture/blob/7c90be0db85a3a3093c766d845d5f278a3d86e16/adr/0079-unique-i …
> OJ-1422: VC Contain Unique Id enabled up to staging

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHanderTest.java
`PostcodeLookupService.java` has been changed so that `RESPONSE_RECEIVED` is sent once we get a response from the post code lookup API. Moved `REQUEST_SENT` to happen before the function call so that it's more clear to when the call happened vs when the response was received. 
The RESPONSE_RECEIVED audit event was missing. 
- [OJ-1597](https://govukverify.atlassian.net/browse/OJ-1597)
[OJ-1597]: https://govukverify.atlassian.net/browse/OJ-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1597: Added the RESPONSE_RECEIVED audit event

- infrastructure/lambda/template.yaml
sizing of deployment infrastructure in the cfn template
Updating build configuration to match production for the performance testing 
- [OJ-1645](https://govukverify.atlassian.net/browse/OJ-1645)
[OJ-1645]: https://govukverify.atlassian.net/browse/OJ-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> oj-1654 update scaling for performance testing

- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
Address entries that are retrieved from the OS Data API are manually set to have a country of `GB`, but this logic was not applied to the Manual address entry.
This PR fixes that.
- [OJ-1776](https://govukverify.atlassian.net/browse/OJ-1776)
[OJ-1776]: https://govukverify.atlassian.net/browse/OJ-1776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Oj 1776/default address country

- .github/workflows/pre-merge-integration-test.yml
Removed parameter overrides in the pre-merge-integration-test template
updated secrets for `di-ipv-cri-dev` environment removed the corresponding repository secrets:
- Github Action role arn
- Artifact bucket name
- Added secret for ordinance survey url in AWS
Stop using the di-ipv-cri-dev in favor of the newer di-ipv-address-cri-dev by specifying the appropriate `Github Action role arn`
B'cos DEV is now working with the keys from the newer `di-ipv-address-cri-dev` and also this help with decomissioning `di-ipv-cri-dev`
> BAU: overrides removed

- infrastructure/lambda/template.yaml
What changed
Removed 4XX alarm from template
Why did it change
So that we are no longer running P1 alerts for 400's in production
> OJ-2075: Remove 4XXX Alarms

- .secrets.baseline
- infrastructure/lambda/template.yaml
Rate Limits in the Usage Plan
HTTP 429s occurred during the performance testing. The usage plan had a smaller burst limit than what was set as the limits for the API gateway. By design, AWS uses the lower value between the Usage Plan and API Gateway. This PR sets them to both be the same.
- [OJ-2113](https://govukverify.atlassian.net/browse/OJ-2113)
[OJ-2113]: https://govukverify.atlassian.net/browse/OJ-2113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2113: Increase usage plan

- build.gradle
By default, SonarCloud sets the project name based on the gradle project name, so it needs to be overriden.
> OJ-2209: Set SonarCloud project name

- lambdas/get-addresses/tsconfig.eslint.json
It shouldn't include all the files in the lambdas/get-addresses directory, only the root config files.
> BAU: Adjust the additional eslint config to only include config files in lambdas/get-addresses root

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
NullPointerException occurs see index="gds_di_production" functionName=address-cri-api-* di-ipv-cri-address-api-postcode-lookup level=ERROR
Log warning instead and return an empty list
NullPointerException maybe causing unwanted UI behavior see ticket
> Incident-641: fix null pointer os api addr

- build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
https://github.com/govuk-one-login/ipv-cri-lib/pull/400
This work is in support of https://govukverify.atlassian.net/browse/DCP-1590 
Modify  event IPV_ADDRESS_VC_ISSUED to capture actual address fields
The address should be mapped into the restricted.address field on the IPV_ADDRESS_VC_ISSUED TXMA Event. The address object is an array of addresses and should be mapped as such.
In order to have consistency across for events for VC Structures, add actual address fields as part of the event as this information needs to be sent downstream to Relying parties. This information will also held the TICF team with their analysis instead of them getting the address for the journey across different events
**Before:**
```
{
"timestamp": 1685334001,
"event_name": "IPV_ADDRESS_CRI_VC_ISSUED", …
```
> OJ-2240: add address to restricted fields

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
Related to https://github.com/govuk-one-login/ipv-cri-address-api/pull/885
`PersonIdentityDetailed` is not mean't to be used directly.
> BAU: stop using deprecated personIdentityDetailed constructor

- build.gradle
cri_common_lib to version 1.5.6
event_timestamp_ms related changes.
- [OJ-2283](https://govukverify.atlassian.net/browse/OJ-2283)
[OJ-2283]: https://govukverify.atlassian.net/browse/OJ-2283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2283: Updated cri_common_lib version

- README.md
see: https://govukverify.atlassian.net/jira/software/c/projects/OJ/boards/502?selectedIssue=OJ-2441
Removed references to PAAS environment which was decommissioned a while ago
Stubs are now AWS
> OJ-2441: updated readme

- .github/workflows/check-pr.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
- .github/workflows/run-integration-tests.yml
- .github/workflows/run-unit-tests-java.yml
- .github/workflows/scan-repo.yml
- build.gradle
- deploy.sh
- infrastructure/lambda/template.yaml
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- integration-tests/src/test/resources/features/AddressAPIHappyPath.feature
- integration-tests/src/test/resources/features/InvalidPostcodeTest.feature
**OJ-2545: Add CloudFront integration tests**
**Tests**
- Check for the device information header in the CRI start message
- Use the SQS and CloudFormation helpers from common-lib
- Update GHA to run the new integration tests
Run integration tests sequentially between PRs to avoid SQS concurrency issues.
- Use `JsonPointer` to make assertions for JSON objects
- Upgrade the version of the common-lib to get the SQS and CF helper
Update the AWS SDK version to match.
**Fixes**
- Use prefixed TxMA exports
The non-prefixed exports are deprecated and will be removed in the future.
- Use the correct secret prefix for local developer stacks
> OJ-2545: Add CloudFront header tests

- build.gradle
- lambdas/postcode-lookup/build.gradle
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
see: https://govukverify.atlassian.net/browse/INCIDEN-751
**NoSuchFieldError** error usually happens due to library incompatibilty changes
https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/lang/NoSuchFieldError.html
java.lang.NoSuchFieldError began when [ipv-cri-lib](https://github.com/govuk-one-login/ipv-cri-lib/pull/335) was updated
and address-cri nimbus libraries became out of sync see below
see: https://gds.splunkcloud.com/en-GB/app/gds-050-digital-Identity/search?earliest=&latest=1703940074.433&q=search%20index%3D%22gds_di_production%22%20address-cri-api-v1-PostcodeLookupFunction*%20NoSuchFieldError&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&display.events.type=list&sid=1718321180.264455
> OJ-2292: Fix no such field error linked to INCIDEN-751 

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHanderTest.java
Rename postcode_error_lookup metric dimension names to be the same for all errors so we can display it in Dynatrace.
Now called postcode_lookup_error_type and postcode_lookup_error_message
Unless the exception had been thrown the metric had not been created in prod/non-prod so we could not create a daashboard in Dynatrace. Giving all the errors dimensions names the same value means we can then filter on the value rather than the key. 
- [OJ-2647](https://govukverify.atlassian.net/browse/OJ-2647)
[OJ-2647]: https://govukverify.atlassian.net/browse/OJ-2647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2647: Rename postcode_error_lookup metric dimension

- lambdas/get-addresses/package-lock.json
- lambdas/get-addresses/package.json
Removed unused aws-sdk 2.x devDependency
AWS has announced that [AWS SDK for JavaScript v2](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) will enter maintenance mode on September 8, 2024
- [OJ-2660](https://govukverify.atlassian.net/browse/OJ-2660)
[OJ-2660]: https://govukverify.atlassian.net/browse/OJ-2660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2660: Remove aws-sdk 2.x devDependency

- .secrets.baseline
- build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/domain/VerifiableCredentialConstants.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/objectmapper/CustomObjectMapper.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/objectmapper/JWTClaimsSetSerializer.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/objectmapper/mixin/AddressMixIn.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/AddressInvalidVc403Test.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/MultipleAddressVcTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/SingleAddressBuildNumberVcTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/SingleAddressBuildingNameVcTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/states/DummyStates.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/states/MultipleAddressStates.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/states/SingleAddressBuildingNameStates.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/states/SingleAddressBuildingNumberStates.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/util/Injector.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/util/JwtSigner.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/util/MockHttpServer.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/util/PreLambdaHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/objectmapper/CustomObjectMapperTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/objectmapper/JWTClaimsSetSerializerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialServiceTest.java
- lambdas/issuecredential/src/test/resources/pacts/addressCriVcPact.json
- lib/build.gradle
Adding PACT provider tests for the VC Issue generation
PACT is a requirement to test integration with the consumer which in this case is `ipv-core`
It test different address VC generation scenarios for address
1. An old address
2. A single Address with building number
3. A single Address with building name instead of building number
4. Multipe Addresses
- [OJ-2650](https://govukverify.atlassian.net/browse/OJ-2650)
[OJ-2650]: https://govukverify.atlassian.net/browse/OJ-2650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2650: Address pact vc

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
This is a followup to: https://govukverify.atlassian.net/browse/OJ-2714
The Handler code has already created, the ConfigurationService, there are default contructor in the AddressCri service i.e. (PostCodeLookupService and VerifiableCredentialService classes create a new instance of the ConfigurationService. 
This PR removes the default Constructors, allows the handler classes to create the dependencies needed by the AddressCri services classes this ensures reusing the existing ConfigurationService instance already created in the handler
> OJ-2714: use one config instance in AddressCri

- .github/workflows/post-merge-deploy-to-dev.yml
- .github/workflows/post-merge-package-for-build.yml
Tested using dev platform upload action in dev workflow ahead of applying it to the build workflow
Post test added change for build as well
The rusty-action action is is no longer maintained and the dev platform have an action that handles the same functionality.
- [IPS-503](https://govukverify.atlassian.net/browse/IPS-503)
- Pacts are failing in the dev workflow but this PR does not make any changes to cause this issue
[IPS-503]: https://govukverify.atlassian.net/browse/IPS-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> replace rusty-actions with dev-platform action

- .cfnlintrc
- build.gradle
- infrastructure/lambda/template.yaml
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/objectmapper/CustomObjectMapper.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/objectmapper/JWSHeaderSerializer.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/MultipleAddressVcTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/SingleAddressBuildNumberVcTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/SingleAddressBuildingNameVcTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/util/PreLambdaHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialServiceTest.java
Add KID to JWT Header
Bump cri_common_lib 3.0.3 -> 3.0.4 -> 3.0.5
Updated VerifiableCredentialService to use the new jwt signing method.
Updated IssueCredentialHandler to handle the NoSuchAlgorithmException. We opted to treat is as a 500 internal error. It is thrown from the new cri-lib method, but it would be very unusal to be thrown especially once pre-merge tests have ran. If this exception is ever thrown we may want to look at a different way to handle it.
Added JWSHeaderSerializer in the PreLambdaHandler, this is to be able to explicitly specify the order of the JWSHeader fields
{
"alg": "HS256",
"typ": "JWT",
"kid": "kid-value"
}
Added and updated unit/pact tests for the above.
- [OJ-2720](https://govukverify.atlassian.net/browse/OJ-2720)
[OJ-2720]: …
> Oj-2720: Add KID to JWT Header

- integration-tests/src/test/resources/cucumber.properties
Remove cucumber publish quiet
It's been deprecated as per the [docs](https://github.com/cucumber/cucumber-js/blob/main/docs/deprecations.md)
> BAU: Remove cucumber publish quiet

- build.gradle
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
`PostcodeLookupService` added a metric `lookup_postcode_duration` to measure the latency between third-party API calls.
This change was added so that we have visibility of how long our API calls to third-parties takes. Primarily, this is to aid bottlenecks in our system.
**Screenshot**
- [OJ-2745](https://govukverify.atlassian.net/browse/OJ-2745)
[OJ-2745]: https://govukverify.atlassian.net/browse/OJ-2745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2745: Add API response metrics and logging

- .cfnlintrc
- infrastructure/lambda/template.yaml
see: 
```
Check Fn::If has a path that cannot be reached] (['Fn::If', 1] is not reachable. 
When setting condition 'IsDevEnvironment' to True. Where existing status for condition `IsNotDevEnvironment` is True)
```
The basically saying the condition `IsDevEnvironment` is never used because of the condition IsNotDevEnvironment applied when the resource is defined therefore the IsDevEnvironment can be removed entirely.
Also removed `Dimensions: []` as flagged by linter
Remove `.cfnlintrc` this was temporary way to ignore the linting issues. due to upgrade of SAM CLI to version 1.123.0 
in the github Action
**NB**
See: https://govukverify.atlassian.net/browse/OJ-2255 which is a related ticket, that's outside the scope of this one.
The `DEV` stack for KBV and ADDRESS are actually more like the …
> OJ-2778: address resolve linting

- README.md
- infrastructure/lambda/template.yaml
- Lambda canary deployment configuration
- Added alarms to Address, IssueCredential, GetAddresses and PostcodeLook up functions.
- Metricerrors alarm and 5xx errors for all but IssueCredential as that does not use APIGW, therefore only Metricerrors alarm added
- Added Code Deploy service role
- Set LambdaDeploymentPreference to AllAtOnce
- Globally set DeploymentPreference to use LambdaDeploymentPreference and Code Deploy service role
- Associated the alarms to specific lambdas
Lambda canary deployment required
- [IPS-1086](https://govukverify.atlassian.net/browse/IPS-1086)
[IPS-1085]: https://govukverify.atlassian.net/browse/IPS-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Canary test in dev:
[IPS-1086]: …
> IPS-1086 address api lambda canary deployment set

- infrastructure/lambda/template.yaml
Setting ActionsEnabled to true for newly deployed canary alarms. 
Enabling alarms from [this PR](https://github.com/govuk-one-login/ipv-cri-address-api/pull/1053)
When ActionsEnabled is set to true when first deploying alarms, it creates slack notifications. As we don't want slack notifications in production, alarms have been switched off in the initial deployment and now switched on.
- [IPA-1086](https://govukverify.atlassian.net/browse/IPS-1086)
> IPS-1086-lambda-canary-alarms-enabled

- infrastructure/lambda/template.yaml
AddressFunctionCanary5xxErrors removed from deployment strategy for canaries.
AddressFunctionCanary5xxErrors removed altogether. 
AddressFunctionCanary5xxErrors alarm is firing off frequently. This is being investigated under [OJ-2821](https://govukverify.atlassian.net/browse/OJ-2821).
For the time being, turning this alarm off so that it doesn't cause a false positive during a deployment and cause a rollback. 
- [IPS-1143](https://govukverify.atlassian.net/browse/IPS-1143)
[OJ-2821]: https://govukverify.atlassian.net/browse/OJ-2821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-1143]: https://govukverify.atlassian.net/browse/IPS-1143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1143 address 5xx canary alarm switched off

- .github/dependabot.yml
Add groups to dependabot following pattern from [core](https://github.com/govuk-one-login/ipv-core-back/blob/main/.github/dependabot.yml).
I am going to test this with address API and roll out to other repos once we're confident that it works for us
Some groups of dependencies (`@aws-sdk` and `eslint`) should be kept in alignment to prevent compatibility issues between them. This PR ensures that dependabot keeps the alignment
> Add groups to dependabot

- infrastructure/lambda/template.yaml
Added a conditional to deploy canary alarms and use canary alarms during deployment only if the deployment strategy is set to all at once.
This stops alarms being triggered in lower envs where canary is not used and when deploying dev or when a PR is raised.
- [IPS-1158](https://govukverify.atlassian.net/browse/IPS-1158)
- Canary alarms no longer created if deployment preference is AllAtOnce
[IPS-1158]: https://govukverify.atlassian.net/browse/IPS-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1158 conditionally deploying canary alarms

- lambdas/get-addresses/src/lib/error-handler.ts
- lambdas/get-addresses/src/lib/session-header.ts
- lambdas/get-addresses/src/services/address-service.ts
- lambdas/get-addresses/src/services/dynamodb-service.ts
- lambdas/get-addresses/src/types/address.ts
- lambdas/get-addresses/src/types/canonical-address.ts
- lambdas/get-addresses/src/types/session.ts
- lambdas/get-addresses/src/v2/get-addresses-v2-handler.ts
- lambdas/get-addresses/src/v2/services/address-service-v2.ts
- lambdas/get-addresses/tests/unit/app.test.ts
- lambdas/get-addresses/tests/unit/get-addresses-v2-handler.test.ts
- lambdas/get-addresses/tests/unit/lib/error-handler.test.ts
- lambdas/get-addresses/tests/unit/services/address-service-v2.test.ts
- lambdas/get-addresses/tests/unit/services/address-service.test.ts
- lambdas/get-addresses/tests/unit/services/dynamodb-service.test.ts
Implement V2 code changes, that will be used to generate the expected structure for the `/addresses/v2` endpoint
Subsequent PR's will connect this up with `/addresses/v2` endpoint
Once merged, am going to continue on the work [here](https://github.com/govuk-one-login/ipv-cri-address-api/pull/1080)
```
{
addresses: [
{
validFrom?: string;
validUntil?: string;
uprn?: string;
organisationName?: string;
departmentName?: string;
subBuildingName?: string;
buildingName?: string;
buildingNumber?: string;
dependentStreetName?: string;
streetName?: string;
doubleDependentAddressLocality?: string;
dependentAddressLocality?: string;
addressLocality?: string;
postalCode?: string;
addressCountry?: string;
}
], // empty array if no addresses
context?: string;
}
```
When receiving a context claim in the …
> OJ-2813: address v2 code

- infrastructure/lambda/template.yaml
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/persistence/item/AddressItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
Added expiryDate to AddressItem and set as TTL
Use the SessionTtl for the AddressTtl as these values should be the same. 
We should only keep data for as long as we need it (especially as it’s PII). Without a TTL to remove it after some time means that we’ll be accumulating unnecessary costs and also eventually breach GDPR.
- [OJ-2810](https://govukverify.atlassian.net/browse/OJ-2810)
[OJ-2810]: https://govukverify.atlassian.net/browse/OJ-2810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2810: Add ttl to Address Table

- build.gradle
- infrastructure/lambda/private-api.yaml
- integration-tests/src/test/java/gov/uk/address/api/client/AddressApiClient.java
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- lambdas/get-addresses/src/types/canonical-address.ts
- lambdas/get-addresses/tests/unit/app.test.ts
- lambdas/get-addresses/tests/unit/get-addresses-v2-handler.test.ts
- lambdas/get-addresses/tests/unit/services/address-service-v2.test.ts
- lambdas/get-addresses/tests/unit/services/address-service.test.ts
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
Bumped cri-lib -> 3.2.1 to now include `addressRegion` in `CanonicalAddress`
Updated unit tests for Java and TS classes that use CanonicalAddress
Amended Integration test to include and check for `addressRegion` in the VC
We need to implement logic that maps the provided international address fields to the One Login address schema so that the address can be included in a Verifiable Credential (VC) and meet the API contract requirements.
`addressRegion` was only added to [CanonicalAddress](https://github.com/govuk-one-login/ipv-cri-lib/blob/main/src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/CanonicalAddress.java)
`CanonicalAddress` is used for the VC Credential Subject and returns like the image below.
[Address](https://github.com/govuk-one-login/ipv-cri-lib/blob/main/src/ …
> OJ-2816: Add addressRegion to CanonicalAddress

- build.gradle
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
Bump cri-lib to 3.4.0, this will ensure addressRegion is also include in the AuditEventContext
Add addressRegion to audit events. 
- [OJ-2816](https://govukverify.atlassian.net/browse/OJ-2816)
[OJ-2816]: https://govukverify.atlassian.net/browse/OJ-2816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2816: Bump cri-lib to include addressRegion in Address

- .github/workflows/run-unit-tests-java.yml
- .github/workflows/run-unit-tests-ts.yml
- .github/workflows/scan-repo.yml
EOL on the 5th December 2024
Also updated version of Sonar Cloud as it needs to use download-artifact v4 as well
https://govukverify.atlassian.net/browse/PSREDEV-1911
https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new
https://github.com/actions/download-artifact?tab=readme-ov-file#v4---whats-new
Updated GH actions
V3 being EOLed 5th Dec
https://govukverify.atlassian.net/browse/PSREDEV-1911
> Updating GitHub provided action to new version

- .github/workflows/check-pr.yml
- .github/workflows/clean-up-deployments.yml
- .github/workflows/code-quality.yml
- .github/workflows/delete-deployment.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/package-for-build.yml
- .github/workflows/package-for-dev.yml
- .github/workflows/run-integration-tests.yml
- .github/workflows/run-pact-tests.yml
- .github/workflows/scan-repo.yml
- .gitignore
- README.md
- deploy.sh
- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/samconfig.toml
- infrastructure/lambda/template.yaml
- settings.gradle
**OJ-2255: Add localdev environment to the template**
- Delete `DevOnlyAddressApi` and use the private API in dev instead
- Set the endpoint configuration and access based on the `localdev` variable
- Add mappings for the `localdev` environment (mirrors `dev`)
- Update the deploy script to use the `localdev` environment
- Add a `samconfig.toml` file with the correct config for `localdev`
- Update the Preview workflow to use the `localdev` environment
- Update integration tests to run with the localdev env
Remove the `pre_merge` prefix from integration test tags since they are all "pre-merge" and adding the same qualifier to each test doesn't help to differentiate between them.
**OJ-2255: Update APIs**
- Update the API config to match other templates
- Use references to the log groups and …
> OJ-2255: Add localdev environment to the template

- integration-tests/src/test/java/gov/uk/address/api/client/AddressApiClient.java
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- integration-tests/src/test/java/gov/uk/address/api/util/AddressContext.java
- integration-tests/src/test/java/gov/uk/address/api/util/AddressContextMapper.java
- integration-tests/src/test/resources/features/AddressAPIHappyPath.feature
- Removal of postcode lookup as part of testing international addresses
- Additional scenario with TxMA headers for international addresses
Added a new step `When the user enters international address successfully`
Updated integration test to use an addressContext class
This ticket is to add full integration tests of the international addresses piece of work.
- [OJ-2820](https://govukverify.atlassian.net/browse/OJ-2820)
[OJ-2820]: https://govukverify.atlassian.net/browse/OJ-2820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2820: vc with international address

- infrastructure/lambda/template.yaml
Introduced `IsDevLikeOrBuild` conditions to cover resources that affect dev, localDev or Build.
The OS Stub Api will be used by pre-merge-test which run in localDev as well as dev and the build environment.
Removed `OrdnanceSurveyAPIURLMapping`
The OrdnanceSurveyAPIKey value has been changed for dev and build accounts placeholder values
/pre-merge-test/OrdnanceSurveyAPIKey
/address-cri-api-v1/OrdnanceSurveyAPIKey
Stop call actual 3rd-party endpoint in lower enviroments.
> OJ-2896: Use Stubs OS Api for Dev & build

- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- integration-tests/src/test/resources/features/AddressAPIHappyPath.feature
- integration-tests/src/test/resources/schema/IPV_ADDRESS_CRI_START.json
- integration-tests/src/test/resources/schema/IPV_ADDRESS_CRI_VC_ISSUED.json
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialServiceTest.java
- Added isUkAddress to VC_ISSUED audit event extensions, this is set to true for UK, IoM and channel islands. 
- Added VC_ISSUED json schema validation to integration tests.
- Fix: Added context field to START event schema validation
So that we can differentiate between UK and international addresses for analytics.
- [OJ-2974](https://govukverify.atlassian.net/browse/OJ-2974)
[OJ-2974]: https://govukverify.atlassian.net/browse/OJ-2974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2974: Add isUkAddress to VC_ISSUED audit event

- infrastructure/lambda/template.yaml
Add env vars to override cache min and max age for secrets manager
So that new API key takes effect within a minute
- [OJ-3001](https://govukverify.atlassian.net/browse/OJ-3001)
[OJ-3001]: https://govukverify.atlassian.net/browse/OJ-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3001: Temporarily lower the secrets manager caching

- build.gradle
- infrastructure/lambda/template.yaml
- lambdas/address/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/postcode-lookup/build.gradle
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
Add OTEL tracing to AWS SDK and Java Http (for Java Lambdas only)
This implementation was copied from here: https://github.com/govuk-one-login/ipv-core-back/pull/2776
This adds instrumentation to the AWS SDK and the Java HTTP client, so that we can see more details traces in dynatrace.
- [OJ-3014](https://govukverify.atlassian.net/browse/OJ-3014)
[OJ-3014]: https://govukverify.atlassian.net/browse/OJ-3014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3014: Open Telemetry Java Lambdas

- build.gradle
- infrastructure/lambda/template.yaml
- lambdas/address/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/postcode-lookup/build.gradle
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
Reverts govuk-one-login/ipv-cri-address-api#1179
Postcode being included in logs, reverting PR to investigate.
> Revert "OJ-3014: Open Telemetry Java Lambdas"

- infrastructure/lambda/template.yaml
Disable annotation from capturing their responses and exception as tracing metadata globally by s
etting environment variables:
POWERTOOLS_TRACER_CAPTURE_RESPONSE and POWERTOOLS_TRACER_CAPTURE_ERROR to false see: https://docs.powertools.aws.dev/lambda/java/core/tracing/
see comments on: https://govukverify.atlassian.net/browse/OJ-3033
These are extract steps, to ensure the leakage from tracing is prevented, currently leaking can be through
api-access-logs are that would be addressed in a future PR
- [OJ-3033](https://govukverify.atlassian.net/browse/OJ-3033)
[OJ-3033]: https://govukverify.atlassian.net/browse/OJ-3033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3033: disable trace annotation capturing

- infrastructure/lambda/template.yaml
Requests to /postcode-lookup/{postode} logs the postcode value in Splunk which users have entered. This PR redacts valid postcode values by masking them. 
Stop logging postcode values from  api gateway private access logs
Postcode is considered to be PII, an actor can potential derive other information about the user. 
- [OJ-3033](https://govukverify.atlassian.net/browse/OJ-3033)
[OJ-3033]: https://govukverify.atlassian.net/browse/OJ-3033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3033: Add redact policy to private access logs

- build.gradle
- infrastructure/lambda/template.yaml
- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
Remove X-Ray tracing, it was observed that the request have the paths which contain postcode.
see comments on: https://govukverify.atlassian.net/browse/OJ-3033
Postcode is considered by the programme as PII, this is one of the steps that can reduce this
> OJ-3033: remove tracing annotation

- infrastructure/lambda/template.yaml
Instead of trying to match with valid postcode, just wildcard anything after the postcode-lookup/ request path
Instead of trying to match with valid postcode, just wildcard anything after the postcode-lookup/ request path
Update to https://github.com/govuk-one-login/ipv-cri-address-api/pull/1189
- [OJ-3033](https://govukverify.atlassian.net/browse/OJ-3033)
[OJ-3033]: https://govukverify.atlassian.net/browse/OJ-3033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3033: Use wildcard

- build.gradle
- infrastructure/lambda/template.yaml
- lambdas/address/build.gradle
- lambdas/issuecredential/build.gradle
Adding OpenTelemetery to Address and IssueCredential Lambdas. This uses auto instrumentation.
The PostcodeLookup handler is slightly more complex and will follow in a different PR.
This adds instrumentation to Address and IssueCredential Java Lambdas so that we can see more details traces in dynatrace.
This follows the previously reverted PR: https://github.com/govuk-one-login/ipv-cri-address-api/pull/1185
- [OJ-3014](https://govukverify.atlassian.net/browse/OJ-3014)
[OJ-3014]: https://govukverify.atlassian.net/browse/OJ-3014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3014: Add OTEL to Address and IssueCredential Java Lambdas

- infrastructure/lambda/private-api.yaml
- integration-tests/src/test/java/gov/uk/address/api/client/AddressApiClient.java
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- integration-tests/src/test/resources/features/PostcodeLookupGetRequest.feature
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHanderTest.java
**Added POST `/postcode-lookup` endpoint.**
Body example: `{ "postcode": "AA11 1AA" }`
- To change the postcode-lookup endpoint to be a POST request with a body instead of a GET request with the postcode PII in the URL (issues with logging) I have updated the APIGW and existing PostcodeLookup lambda to handle both GET and POST requests.
- Refactored lambda unit tests to include tests for both POST and GET. When GET is removed these tests will need removing and only the POST ones need to remain. The majority of tests only include POST requests.
- Updated the existing integration tests to now use the POST postcode-lookup endpoint. (Note: To ensure GET postcode-lookup endpoint is still tested, added a new feature file which can easily be deleted when GET endpoint is removed)
We want to …
> Oj 3037 post postcode lookup endpoint

- lambdas/postcode-lookup/build.gradle
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
Added OpenTelemetery to Postcode Lookup Lambdas.
Now the /postcode-lookup endpoint is not invoked by a URL containing the postcode (PII). We can re-enable OTEL on this lambda/endpoint.
This adds instrumentation to Postcode Lookup Java Lambda so that we can see more details traces in dynatrace.
Previously reverted in: https://github.com/govuk-one-login/ipv-cri-address-api/pull/1185
Other Java Lambdas OpenTelemetry added in this PR: https://github.com/govuk-one-login/ipv-cri-address-api/pull/1194
- [OJ-3014](https://govukverify.atlassian.net/browse/OJ-3014)
[OJ-3014]: https://govukverify.atlassian.net/browse/OJ-3014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3014: Add OTEL to PostcodeLookupHandler

- infrastructure/lambda/template.yaml
Reverts govuk-one-login/ipv-cri-address-api#1193
as part of https://govukverify.atlassian.net/browse/OJ-3039
> OJ-3039: Revert "OJ-3033: Adjust regex"

- infrastructure/lambda/template.yaml
see: https://github.com/govuk-one-login/ipv-cri-address-api/pull/1199
Removed the the GET /postcode-lookup/{postcode} endpoint since the POST equivalent is now being used by see https://github.com/govuk-one-login/ipv-cri-address-front/pull/1091 we no longer need to redact.
We've re-implemented the get endpoint as post to
migitated having to redaction postcode-lookup urls
- [OJ-3039](https://govukverify.atlassian.net/browse/OJ-3039)
[OJ-3039]: https://govukverify.atlassian.net/browse/OJ-3039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3039: Remove data redaction policy

- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/handler/PostcodeLookupHandler.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/pii/PiiPostcodeMasker.java
- lambdas/postcode-lookup/src/main/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupService.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/pii/PiiPostcodeMaskerTest.java
- lambdas/postcode-lookup/src/test/java/uk/gov/di/ipv/cri/address/api/service/PostcodeLookupServiceTest.java
In some cases a postcode request to OS Places API, results in a response where the API was unable to find a record for a
request and it tries to be helpful by suggesting there was an issue with the postcode value used to make the request. These values maybe close to actual postcode values for instance user may have enter a 5 instead of an S. This PR mask the postcode values found in such responses
Postcode like values are seen in responses to bad request
The program considers postcode as PII, this PR mask any cases of these values
- [OJ-3044](https://govukverify.atlassian.net/browse/OJ-3044)
[OJ-3044]: https://govukverify.atlassian.net/browse/OJ-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3044: PII postcode look function

- build.gradle
bump ipv-cri-lib to version 4.0.0
* Keeps our dependencies up to date.
* 4.0.0 has updates for OTEL.
* We also need to upgrade the dependency to support SnapStart.
- [OJ-3054](https://govukverify.atlassian.net/browse/OJ-3054)
[OJ-3054]: https://govukverify.atlassian.net/browse/OJ-3054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> deps: bump ipv-cri-lib to version 4.0.0

- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
KMSClient is being referenced from the ServiceFactory instead of manually creating it.
To support SnapStart, we have to handle credentials differently. The ServiceFactory is a wrapper over ClientProviderFactory which is provided from ipv-cri-lib. The ClientProviderFactory gives us a SnapStart suitable reference of the KMSClient that we can use.
- [OJ-3055](https://govukverify.atlassian.net/browse/OJ-3055)
[OJ-3055]: https://govukverify.atlassian.net/browse/OJ-3055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: use kms client from ClientProviderFactory in IssueCredentialHandler

- .pre-commit-config.yaml
- infrastructure/lambda/template.yaml
- Upgrade node runtime from 18 -> 22 for the Addresses Lambda. 
- Bump to cfn-lint in the pre-commit config to support node 22 being a valid runtime.
Node 18 has reached end of active live support 
- [OJ-3068](https://govukverify.atlassian.net/browse/OJ-3068)
[OJ-3068]: https://govukverify.atlassian.net/browse/OJ-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3068: Upgrade lambda node runtime to 22

- .github/workflows/package-for-build.yml
- .github/workflows/package-for-dev.yml
Remove `Setup SAM` step from the post merge deploy dev & build GHA. 
SAM CLI 1.132.0+ is needed to support node 22 runtimes. `unbuntu-latest` image already comes with SAM CLI installed (and is a much newer version)
- [OJ-3068](https://govukverify.atlassian.net/browse/OJ-3068)
[OJ-3068]: https://govukverify.atlassian.net/browse/OJ-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3068: Remove Setup SAM step

- build.gradle
- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/template.yaml
- Bump cri-lib to 4.1.0 to include the new validateSession logic
- Re-enable `AddressFunctionCanary5xxErrors`
- Set `x-amazon-apigateway-request-validator` to `Validate both` so requests without the `session_id` header return a 400.
You can get through to the confirm page on a UK journey without a session, this should be handled separately, but we still want to handle this and return a 4XX error instead of a 5XX.
cri-lib `v4.1.0` contains new logic to handle `validateSession` being passed an 'empty' String. Instead of a `DynamoDBException` being returned which is not handled, a `SessionNotFoundException` will be returned.
- [OJ-2821](https://govukverify.atlassian.net/browse/OJ-2821)
[OJ-2821]: https://govukverify.atlassian.net/browse/OJ-2821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> OJ-2821: Bump cri-lib and re-enable Address5xx Canary

- infrastructure/lambda/template.yaml
- Set provision concurrency to 0 in build
- Added provision concurrency only to `GetAddressesFunction` typescript lambda
As provisioned concurrency does not work alongside SnapStart. 
- [OJ-3053](https://govukverify.atlassian.net/browse/OJ-3053)
[OJ-3053]: https://govukverify.atlassian.net/browse/OJ-3053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3053: update - set provision concurrency to 0 for build

- infrastructure/lambda/template.yaml
- Enabled snap start for all java lambdas in Address
To improve our cold start performance.
- [OJ-3056](https://govukverify.atlassian.net/browse/OJ-3056)
[OJ-3056]: https://govukverify.atlassian.net/browse/OJ-3056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3056: feat - enable snap start on java lambdas

- infrastructure/lambda/template.yaml
- Set provision concurrency in Prod to 0
- To enable snap start to be configured in Prod
- [OJ-3058](https://govukverify.atlassian.net/browse/OJ-3058)
[OJ-3058]: https://govukverify.atlassian.net/browse/OJ-3058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3058: update - remove provision concurrency in prod

- infrastructure/lambda/template.yaml
- Removed condition to disable to snapstart for production
To enable snapstart for production.
- [OJ-3058](https://govukverify.atlassian.net/browse/OJ-3058)
[OJ-3058]: https://govukverify.atlassian.net/browse/OJ-3058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3058: feat - enable snap start to production

- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/handler/IssueCredentialHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
Remove use of deprecated DataStore.getClient method
When investigating 502 errors in production we noticed that the way AddressService sets up EnhancedDynamoDbClient is different to SessionService and could be causing issues now that we have snapstart enabled
- [OJ-3124](https://govukverify.atlassian.net/browse/OJ-3124)
[OJ-3124]: https://govukverify.atlassian.net/browse/OJ-3124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3124: Remove use of deprecated DataStore.getClient method

- lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java
- lambdas/address/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
Get addressTtl from configurationService and remove hardcoding
The hard coding was just to test the theory that the NullPointerExceptions were being caused by a dodgy TTL. 
Now that we have confirmed this is the case, we can remove the hard coding and use the service as originally suggested, but with the variable defined at a scope that means it will not be saved in the snapshots for snapstart.
- [OJ-3124](https://govukverify.atlassian.net/browse/OJ-3124)
[OJ-3124]: https://govukverify.atlassian.net/browse/OJ-3124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3124: Get addressTtl from configurationService

- lambdas/pii-redact/src/pii-redact-handler.ts
pii-redact-handler.ts
The log group name was changed and the handler used a hardcoded postfix to find the log group. This meant the redactor couldn't find the target log group to store the redacted logs.
**Screenshots**
- [OJ-2862](https://govukverify.atlassian.net/browse/OJ-2862)
[OJ-2862]: https://govukverify.atlassian.net/browse/OJ-2862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: pii-redact-handler.ts

- integration-tests/src/test/java/gov/uk/address/api/client/AddressApiClient.java
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- integration-tests/src/test/resources/features/AddressUnhappyPath.feature
What changed
Added no session_id header and no postcode in the request body to the unhappy path Java cucumber API tests
Why did it change
There is a need for additional no session_id header and no postcode in the request body to ensure endpoints are working correctly and if these conditions are satisfied: (a) no session_id (b) with session_id and no postcode (c) with postcode and no session_id. The endpoint should return a 400 HTTP status code.
ScreenShot
> Oj 3135 address-api-add unhappy path

- build.gradle
- gradle/libs.versions.toml
- lambdas/address/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/postcode-lookup/build.gradle
- lib/build.gradle
This was raised to remove the duplication and redundancy in our build.gradle files for example, we introduced dependencies into the sub modules via the parent build.gradle that were not needed by the sub modules. 
Additionally, removed a lot of the duplication. 
- [OJ-3154](https://govukverify.atlassian.net/browse/OJ-3154)
[OJ-3154]: https://govukverify.atlassian.net/browse/OJ-3154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: better organise build.gradle

- lambdas/pii-redact/src/pii-redact-handler.ts
- step-functions/add-expiry-to-addresses.asl.json
* Increase sleep to 10 seconds for add-expiry-date step function
* Add a 1second wait before creating log stream as create log stream has a 50 tps rate limit. 
We were getting 400 responses in Dynatrace for https://logs.eu-west-2.amazonaws.com/
https://govukverify.atlassian.net/browse/OJ-2862
> feat: increase sleep to 10 seconds

- infrastructure/lambda/template.yaml
Add new SessionLambdaFailedToVerifyJWTAlarm and TokenLambdaFailedToVerifyJWTAlarm alarms
So that we are quickly alerted when there is an issue verifying the JWTs that core is sending address CRI. 
The new metric has been added in common lambdas https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/465
- [OJ-3075](https://govukverify.atlassian.net/browse/OJ-3075)
[OJ-3075]: https://govukverify.atlassian.net/browse/OJ-3075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3075: Add FailedToVerifyJWTAlarm alarms

- infrastructure/lambda/template.yaml
Add condition to ensure alarms are not required in dev
Existing condition is wrong
Discovered while documenting and testing runbooks for these alarms 
- [OJ-2969:(https://govukverify.atlassian.net/browse/OJ-2969:
> OJ-2969: Correct condition on JSONWebKey Api alarms

- infrastructure/lambda/public-api.yaml
- infrastructure/lambda/template.yaml
- Hardcode bucket name
- Remove dependency on export from core-infrastructure-stack
- Fix `Update canceled. Cannot update export core-infrastructure-PublishedKeysS3BucketName as it is in use by address-cri-api-v1.`
- [IPS-1722](https://govukverify.atlassian.net/browse/IPS-1722)
[IPS-1722]: https://govukverify.atlassian.net/browse/IPS-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1722: Update bucket name

- infrastructure/lambda/template.yaml
Turn JsonWebKeys4XXApiGwErrorAlarm on
As it is only a warning alarm it's safe to turn on
- [OJ-3179](https://govukverify.atlassian.net/browse/OJ-3179)
[OJ-3179]: https://govukverify.atlassian.net/browse/OJ-3179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3179: Turn JsonWebKeys4XXApiGwErrorAlarm on

- infrastructure/lambda/private-api.yaml
- infrastructure/lambda/public-api.yaml
To add canary deployment in common lambda functions, the api spec should point to the live alias of the common lambda function. 
Modified the api spec point to the live common lambda functions.
Changes for api spec point to live lambda functions. This changes made for the common lambda functions include 
Session function
Authorization function 
Access Token function.
To enable canaries for the common lambda function
- [IPS-1862](https://govukverify.atlassian.net/browse/IPS-1862)
[IPS-1862]: https://govukverify.atlassian.net/browse/IPS-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1862: Update api spec point to live alias of the lambda function

- integration-tests/src/test/java/gov/uk/address/api/client/AddressApiClient.java
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- integration-tests/src/test/resources/features/AddressAPIHappyPath.feature
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/address/api/service/VerifiableCredentialService.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/service/AddressService.java
- lib/src/main/java/uk/gov/di/ipv/cri/address/library/util/CountryCode.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/service/AddressServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/address/library/util/CountryCodeTest.java
DVLA has reported validation issues due to inconsistent formatting of postcodes, submitted via our address entry field this include  postcodes containing extra or irregular white spaces this is as expected see https://design-system.service.gov.uk/patterns/addresses/
However, when user has committed to address changes; the post code should be stored in a way as to prevent  reported validation issues
Store postcode with any validation issues
**Postcode with trailing space and extra space in the middle**
**Click on Change link**
**Confirm your details appear like this**
**Click on all change link reveals - post code is still with spaces**
Postcode in dynamodb is with spaces
**NB:**
Added a scenario in `AddressAPIHappyPath.feature` called `uk_address_save_address_remove_spaces_from_postcode` …
> OJ-3313: Save Trimmed Postcode

- .github/workflows/deploy-branch.yml
- .github/workflows/package-for-build.yml
- .github/workflows/package-for-dev.yml
- .github/workflows/run-integration-tests.yml
- .github/workflows/run-pact-tests.yml
- .github/workflows/run-unit-tests-java.yml
- .github/workflows/scan-repo.yml
- infrastructure/lambda/template.yaml
Adds Ordnance Survery API URL SSM params for different clients, example SSM param name: `"/${AWS::StackName}/OrdnanceSurveyAPIUrl/ipv-core"`
Fixed gradle version issue in GHA's, original KBV PR here: https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/534
Create the SSM params to allow (in future PRs) Core and other consumers to dynamically configure whether the stub or real API should be used, depending on the Client ID provided 
- [OJ-3274](https://govukverify.atlassian.net/browse/OJ-3274)
[OJ-3274]: https://govukverify.atlassian.net/browse/OJ-3274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3274: Add OS API URL SSM params per client

- infrastructure/lambda/private-api.yaml
- integration-tests/src/test/java/gov/uk/address/api/client/AddressApiClient.java
- integration-tests/src/test/java/gov/uk/address/api/stepdefinitions/AddressSteps.java
- integration-tests/src/test/resources/features/AddressUnhappyPath.feature
Adds regex to reject `0000` as the date year for `validFrom` and `validTo` in the API Address schema. 
Added an integration test to test this.
If a request is sent to our `/address` with a `validFrom` or `validUntil` year of `0000` the deserialisation will error as LocalDate does not see `0000` as a valid date year. 
We have implemented a fix FE https://github.com/govuk-one-login/ipv-cri-address-front/pull/1209 but we also want to harden our endpoint to prevent `0000` causing `5XX` errors.
- [OJ-3115](https://govukverify.atlassian.net/browse/OJ-3115)
[OJ-3115]: https://govukverify.atlassian.net/browse/OJ-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3115: Reject dates on address endpoint with year 0000

- infrastructure/lambda/template.yaml
In this [PR](https://github.com/govuk-one-login/ipv-cri-address-api/pull/1338) I didn't notice that the Layer wasn't **global**
therefore only **PostcodeLookupFunction** has up to date dynatrace layer - since I have also merged the [following](https://github.com/govuk-one-login/ipv-cri-address-api/pull/1339)
This PR updates the other function layers to there corresponding values in AWS as the **FIRST** phase of hard coding
Subsequent PR will update to the latest
see: below screen shots
**DONE** - **PostcodeLookupFunction**
This PR requires **FIRST PHASE UPDATE** from the old dynamic approach
**AddressFunction**
**GetAddressFunction**
**IssuecredentialFunction**
- [OJ-3394](https://govukverify.atlassian.net/browse/OJ-3394)
[OJ-3394]: …
> OJ-3394: Hard code the other individual function layers

- build.gradle
- gradle/libs.versions.toml
- Updated the version for `aws-bom` and `nimbusdus-oauth` to fix the issues raised by dependabot. Updated the main dependencies to fix the transitive dependencies listed [here](https://github.com/govuk-one-login/ipv-cri-address-api/security/dependabot)
- Updated `common-lib` and `spotless` dependency to latest as well.
N.B: unable to upgrade `powertools` dependency to the latest as it removes the `org.apache.logging.log4j` imports. When using the `slf4j logger` imports in replace of this, the `couldn't find aspectjrt.jar on classpath` error kept appearing due to having this `aspect libs.bundles.powertools` within the build.gradle file. Unable to update au.com.dius.pact:provider dependency as the vulnerability is still in the latest release …
> OJ-3439: Fix dependabot issues

- infrastructure/lambda/template.yaml
As part of transitioning FMS WAF rule enforcement from COUNT to BLOCK, Security have set up custom policies for us to apply to our resources in scope. In COUNT mode FMS merely logs the rule violations, in BLOCK mode violating requests are actively blocked. 
The tags to implement this should only apply (conditionally) to resources deployed to dev, build and staging accounts. The tags must not apply to int and prod (there is a follow-up ticket for this:
Apply tagging conditional to meet the above requirement
Part of transitioning FMS WAF rule enforcement
**Tags on ApiGateway**
- [OJ-3444](https://govukverify.atlassian.net/browse/OJ-3444)
[OJ-3444]: https://govukverify.atlassian.net/browse/OJ-3444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3444: Conditionally include FMSRegionalPolicy
